### ISSUE TITLE
[Question] Speeding up building RoutingGraph

### ISSUE THREAD

**Issue by tkkhuu** [fzi-forschungszentrum-informatik/Lanelet2#10]
For a larger map, the routing graph builder (lanelet::routing::RoutingGraph::build) can take quite some time. I know there is the option to get a debug routing graph, but is there a way to cache the RoutingGraph object into a file and retrieve it in later run?

**Comment by poggenhans** [comment]
Sorry, currently not. Dumping and loading the routing graph is not so trivial, because all map data and all other routing graphs have to be dumped with it. Otherwise the data would be inconsistent with the originally loaded map.

There is also still potential for optimizing the builder itself. Afaik, most of the time goes into computing conflicting lanelets. Speeding this up could also help mitigating this issue.

**Comment by tkkhuu** [comment]
I see, thank you! Is there any other way that you recommend that could speed up this process?

**Comment by poggenhans** [comment]
Hm, that depends on your application, I guess. If you are only interested in a specific route, you could  use the route object to generate a sub-map for you (using `Route::laneletMap`) that only contains the lanelets that you need for this specific route. Depending how big your original map was, only working on this sub-map and creating the RoutingGraphs from this one would surely speed up things.

**Comment by matthiashh** [comment]
While not having measured it, I would also assume that most time goes into determining conflicts between lanelets. 

If you don't need those relations it would be easy to introduce a configuration parameter for `RoutingGraph::Configuration`.
If a performance analysis shows that most time is spend in the `addConflictingEdge` function one could also think about parallelizing that part, right? It just needs read access on `passableLanelets` and we could add all the edges to the graph at once when we finished finding all the conflicts.

**Comment by tkkhuu** [comment]
I see, thank you !

**Comment by Shelfcol** [comment]
I'm Gu Xuefeng from China.Sorry to interrupt you. I am new to Ubuntu ,so I don't know CMakeLists.txt well.I get to know you once used lanelet2 library in your project.Can you tell me what I should add in my CMakeLists.txt to link lanelet2 library.My project locates in catkin_ws/src,and CMakeLists.txt locates in catkin_ws/src/my_project. lanelet2 and mrt_cmake_modules locate in catkin_ws/src. And lanelet2 already catkin_make succeeded. I am looking forward to your reply. Thank you very much. @tkkhuu
