### ISSUE TITLE
Is the ROS build farm release broken?

### ISSUE THREAD

**Issue by hadiTab** [fzi-forschungszentrum-informatik/Lanelet2#102]
I see lanelet2 listed here: https://github.com/ros/rosdistro/blob/master/melodic/distribution.yaml#L4418
But I'm not able to install using apt. I keep on getting the `E: Unable to locate package ros-melodic-lanelet2...` error.

**Comment by poggenhans** [comment]
Its not broken, it just takes its time. Lanelet2 has just been merged and it should be available with the next sync from the testing to the official stable repository in the next few weeks.
