### ISSUE TITLE
Create Linestring3d with variable number of Points

### ISSUE THREAD

**Issue by fabianwb** [fzi-forschungszentrum-informatik/Lanelet2#105]
Hi,
Is there a posibility to create a Linestring3d with a variable number of Points?
I want to build a Linestring but I have a unknown quantity of Points in a array. Can I call the function with these or do I have to hand over each point individually to the function?

Thanks and best regards

**Comment by poggenhans** [comment]
You mean by using the constructor? You can just pass a vector of Point3d to [this constructor](https://gitlab.mrt.uni-karlsruhe.de/MRT/released/lanelet2/-/blob/master/lanelet2_core/include/lanelet2_core/primitives/LineString.h#L227).

Alternatively you can also use `insert`. That should work on any container, not only vector:
```c++
std::array<Point3d> points;
LineString3d ls;
ls.insert(ls.end(), points.begin(), points.end());
```

**Comment by poggenhans** [comment]
This issue has been inactive for a while. I'm assuming the original question has been answered.
