### ISSUE TITLE
Python3 segmentation fault

### ISSUE THREAD

**Issue by jpaczia** [fzi-forschungszentrum-informatik/Lanelet2#109]
Running `python3 -c "import lanelet2"` causes an segmentation fault, the output is the following:
```
$ python -c "import lanelet2"                                                                                                                                             
[1]    6576 segmentation fault (core dumped)  python3 -c "import lanelet2"
$ 
``` 

I built lanelet2 as described in the readme and in issue #93 without problems.
I assume it was configured correct, the line `Found PythonInterp: /usr/bin/python3.6 (found version "3.6.9")` was printed.

I am using Kubuntu 18.04 (tried also Ubuntu 18.04), both were completely new installed. 
The installed versions of CMake are 3.10.2 (installed as dependency) and 3.17.1 (installed via snap).
Apparently I can't remove CMake 3.10.2, because the package `ros-melodic-catkin` depends on the CMake package (at least the output of the command `sudo dpkg --remove cmake` says so).

**Comment by poggenhans** [comment]
Hard to tell what went wrong there. You could try launching the whole thing in the debugger ( `gdb -ex run --args python -c "import lanelet2"`), and see where it breaks.

Looking at the output of `ldd` for the generated binary might also be helpful (e.g `ldd /path/to/workspace/devel/lib/python3.6/dist-packages/lanelet2/core.so`).

**Comment by jpaczia** [comment]
gdb shows that the following error occured: `GlobalError::PushToStack() () from /usr/lib/x86_64-linux-gnu/libapt-pkg.so.5.0`
According to [this](https://stackoverflow.com/a/57065341) the wrong boost version is used.

Running `ldd devel/lib/python3/dist-packages/lanelet2/core.so` results in the following output:
```
linux-vdso.so.1 (0x00007fff09deb000)
libboost_python-py27.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.65.1 (0x00007f4bb4614000)
libpython3.6m.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0 (0x00007f4bb3f69000)
liblanelet2_core.so.1 => /home/jonas/catkin_ws/devel/lib/liblanelet2_core.so.1 (0x00007f4bb3bc8000)
libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4bb383f000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4bb3627000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4bb3236000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4bb3017000)
libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f4bb2de5000)
libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f4bb2bc8000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4bb29c4000)
libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f4bb27c1000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4bb2423000)
/lib64/ld-linux-x86-64.so.2 (0x00007f4bb4e28000)
``` 

The second line confirms that the boost version for python2 is used.
Do I need to configure anything else than `catkin config --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo -DPYTHON_VERSION=3.6` to build for python3?

**Comment by poggenhans** [comment]
It seems CMake doesn't find the correct boost python version for you. We already had some troubles with that, because the approach needed to make CMake do the right thing seems to different with every cmake/python/boost version combination (see also #93).

You should have a look into [our findscript for boost python](https://github.com/KIT-MRT/mrt_cmake_modules/blob/master/cmake/Modules/FindBoostPython.cmake). Maybe that helps you to find a minimum working example so that we can find out what is going wrong on your system.

**Comment by jpaczia** [comment]
I am not very familiar with CMake, so I am not sure what to look at in the findscript for python.

I think the script selects the wrong python version on my system, so I run `cmake -LAH` - which displays the variables and their values (according to [stackoverflow](https://stackoverflow.com/questions/9298278/cmake-print-out-all-accessible-variables-in-a-script/18839117#18839117)) - in the lanelet2_python directory. 
Here the line `Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.17", minimum required is "2")` is printed, so I assume my configuration went somehow wrong.

The default python version is set to python3, as describe [here](https://unix.stackexchange.com/questions/410579/change-the-python3-default-version-in-ubuntu).

Just to make sure I am not missing any step / execute the commands in the wrong order, here my steps:
```
source /opt/ros/$ROS_DISTRO/setup.bash
mkdir catkin_ws && cd catkin_ws && mkdir src
pip3 install --user catkin_pkg
python3 -m venv env
source env/bin/activate  # (also tried skipping this step)
catkin init
catkin config --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo -DPYTHON_VERSION=3.6
cd src && git clone https://github.com/fzi-forschungszentrum-informatik/lanelet2.git && cd ..
catkin build -v
```

**Comment by jpaczia** [comment]
Running the same steps in bash, the compiling fails due to the following error in lanelet2_core:

```
Make Error at /opt/ros/melodic/share/mrt_cmake_modules/cmake/Modules/GatherDeps.cmake:34 (message):
  Gather depenencies failed: Traceback (most recent call last):

    File "/opt/ros/melodic/share/mrt_cmake_modules/cmake/../scripts/generate_cmake_dependency_file.py", line 34, in <module>
      import ast.literal_eval as eval_expr

  ModuleNotFoundError: No module named 'ast.literal_eval'; 'ast' is not a
  package

Call Stack (most recent call first):
  CMakeLists.txt:11 (include)

```

As far as I know there should be no difference between zsh and bash in this matter, am I right?

**Comment by poggenhans** [comment]
Ah, sorry, I just saw you are using the ROS version of [`mrt_cmake_modules`](https://github.com/KIT-MRT/mrt_cmake_modules). Could you first try to clone the current version directly into to your workspace? We fixed a couple of things there regarding python3.

**Comment by jpaczia** [comment]
Cloning the current version into the workspace solved the problem. I think this should be mentioned in the python3 section of the readme.
Thanks for your help!
