### ISSUE TITLE
[Question] Python3

### ISSUE THREAD

**Issue by dbenz3** [fzi-forschungszentrum-informatik/Lanelet2#11]
Hi,
I would like to ask if there is also a Python3 binding or if it is planned for the future?
My whole project is written in Python3 and I want to use lanelet2 to generate maps.
Thanks in advance

**Comment by poggenhans** [comment]
Yes, it is planned. Its not an actual problem within the bindings itself (they are mostly compatible), its more a problem on the cmake/catkin side, since catkin's support for python 3.x is a bit brittle. Once we solved that, we should be able to officially support it.
