### ISSUE TITLE
Fail to Build Docker Image

### ISSUE THREAD

**Issue by OscarWan** [fzi-forschungszentrum-informatik/Lanelet2#110]
When I clone the repository and follow the instruction of installation to build docker image, (the corresponding code is `docker build -t lanelet2 .`, there are some error messages showing like this:

> Errors << lanelet2_core:make /home/developer/workspace/logs/lanelet2_core/build.make.000.log
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [CMakeFiles/lanelet2_core.dir/src/LaneletMap.cpp.o] Error 4
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/lanelet2_core.dir/all] Error 2
make: *** [all] Error 2
cd /home/developer/workspace/build/lanelet2_core; catkin build --get-env lanelet2_core | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...............................................................................
Failed << lanelet2_core:make                     [ Exited with code 2 ]
..............................................................................................................
Profile:                     default
Extending:             [env] /opt/ros/melodic
Workspace:                   /home/developer/workspace
..............................................................................................................
Build Space:        [exists] /home/developer/workspace/build
Devel Space:        [exists] /home/developer/workspace/devel
Install Space:      [unused] /home/developer/workspace/install
Log Space:         [missing] /home/developer/workspace/logs
Source Space:       [exists] /home/developer/workspace/src
DESTDIR:            [unused] None
..............................................................................................................
Devel Space Layout:          linked
Install Space Layout:        None
..............................................................................................................
Additional CMake Args:       -DCMAKE_BUILD_TYPE=RelWithDebInfo
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
..............................................................................................................
Whitelisted Packages:        None
Blacklisted Packages:        None
..............................................................................................................
Workspace configuration appears valid.
NOTE: Forcing CMake to run for each package.
..............................................................................................................
[build] Found '11' packages in 0.0 seconds.                                    
[build] Updating package table.                                                
Starting >>> catkin_tools_prebuild                
Finished <<< catkin_tools_prebuild                 [ 3.5 seconds ]
Starting >>> mrt_cmake_modules                    
Finished <<< mrt_cmake_modules                     [ 2.4 seconds ]
Starting >>> lanelet2_core                        
Failed <<< lanelet2_core                         [ 10 minutes and 28.5 seconds ]
Abandoned <<< lanelet2_io                           [ Unrelated job failed ]
Abandoned <<< lanelet2_maps                         [ Unrelated job failed ]
Abandoned <<< lanelet2_projection                   [ Unrelated job failed ]
Abandoned <<< lanelet2_traffic_rules                [ Unrelated job failed ]
Abandoned <<< lanelet2_routing                      [ Unrelated job failed ]
Abandoned <<< lanelet2_python                       [ Unrelated job failed ]
Abandoned <<< lanelet2_examples                     [ Unrelated job failed ]
Abandoned <<< lanelet2_validation                   [ Unrelated job failed ]
[build] Summary: 2 of 11 packages succeeded.
[build] Ignored: 1 packages were skipped or are blacklisted.
[build] Warnings: None.
[build] Abandoned: 8 packages were abandoned.
[build] Failed: 1 packages failed.
[build] Runtime: 10 minutes and 34.7 seconds total.
[build] Note: Workspace packages have changed, please re-source setup files to use them.
The command '/bin/sh -c /bin/bash -c "source /opt/ros/$ROS_DISTRO/setup.bash && catkin build --no-status"' returned a non-zero code: 1

I am wondering how to fix this bug. Any suggestions are appreciable!

**Comment by poggenhans** [comment]
This `c++: internal compiler error: Killed (program cc1plus)` indicates the kernel killed the compiler because he did something he shouldn't do. The most likely reason ist that he tried to allocate more memory than available.

You could try to change the last line in the dockerfile to `RUN /bin/bash -c "source /opt/ros/$ROS_DISTRO/setup.bash && catkin build --no-status -j1`. Compilation will take a lot longer but since there is only one compiler job running at a time, it is more likely that it will not run out of memory.

**Comment by OscarWan** [comment]
Thanks for your quick responding! I tried what you suggest several rounds, but the computer is just running for much more time without ending (around one and a half hour for one try). I am wondering whether the setup is not suitable for locally installing?

p.s.: There's just a small typo in your suggestion -- one `"` is missing after `-j1`.

**Comment by poggenhans** [comment]
Your problem sounds similar to #94. Which OS are you using? You could try to leave the "--no-status" out, to see where exactly it is stuck. The docker build should be functional, our CI is not releasing anything on the master branch without testing the docker image first. It must be something special about your system.

Since lanelet2 has been released for ROS, you could also just install the ros package in your docker container and be done (`sudo apt install ros-melodic-lanelet2`).
