### ISSUE TITLE
Memory leak via Python API

### ISSUE THREAD

**Issue by hobodylan** [fzi-forschungszentrum-informatik/Lanelet2#111]
Memory leaks somewhere when Lanelet2 is used via its boost python API ( both python 2 and 3 ). It worked without leaks when I created the same class in a C++ program.

See the script which prints the symptoms.

The reference count to 'points' list keeps increasing - I managed to stop that by not using python::borrowed handler in the IterableConverter struct, although I am not sure if that was right to do. Anyway it didn't solve the memory leak, it was still present after my hack.

`
import lanelet2
import time
import os
import gc
import sys

points = []
attribute = lanelet2.core.AttributeMap()

def print_memory_usage():
    with open('/proc/self/status') as f:
        mem_usage = f.read().split('VmRSS:')[1].split('\n')[0][:-3]
    print("Memory in MB: " + str(int(mem_usage.strip()) / 1024))

def create_line_string():
    global points
    global attribute
    dummy_var =  lanelet2.core.LineString3d(lanelet2.core.getId(), points, attribute)

def main():
    gc.enable()
    for i in range(1000000):
        create_line_string()

        if i % 1000 == 0:
            gc.collect()
            print_memory_usage()
            print("points ref count: " + str(sys.getrefcount(points)))
            print("attribute ref count: " + str(sys.getrefcount(attribute)))

if __name__ == "__main__":
    main()
`

**Comment by poggenhans** [comment]
Thank you for that minimal example, that was very helpful in tracking down the problem! The fix should arrive here soon.

It turned out the `convertible` funcition was cluttering the refcount, because an object was created there that was never deleted.

The memory leak that you observed is rather a problem with how you use the garbage collector. If you replace your code with
```python
while gc.collect():
    pass
```
the "leak" goes away.

**Comment by hobodylan** [comment]
Thanks a lot for the quick fix @poggenhans !
