### ISSUE TITLE
How to create lanelet Map for complex roads on heights ?

### ISSUE THREAD

**Issue by arvindkyutech** [fzi-forschungszentrum-informatik/Lanelet2#113]
![Issue1](https://user-images.githubusercontent.com/62092870/81533679-93fbec80-93a1-11ea-97bb-6d2c6e8d1a83.png)
![Issue2](https://user-images.githubusercontent.com/62092870/81533684-965e4680-93a1-11ea-81cb-c8c40deb5042.png)
How to create Lanelet Maps when Road goes below flyover and merge?

**Comment by poggenhans** [comment]
What problems are you experiencing? This should be straightforward. Just use the `ele` tag to properly assign a height for the elevated road sections.

**Comment by arvindkyutech** [comment]
Elevation of flyovers changes gradually and finally merge somewhere in lanes. Actually, how to represent this gradual change in height of flyovers.

**Comment by poggenhans** [comment]
Ah, well if you don't have access to elevation data, you could consider writing a small python script and  manipulate the z-coordinate of the points using the python bindings of lanelet2.

**Comment by poggenhans** [comment]
This issue has been inactive for a while. I'm assuming the original problem has been resolved.
