### ISSUE TITLE
findWithin2d / findWithin3d not found in python

### ISSUE THREAD

**Issue by ConstantinB9** [fzi-forschungszentrum-informatik/Lanelet2#117]
I was trying to use findWithin2d using python. I guessed it should be available like this:
```
lanelet2.geometry.findWithin2d(primitive_layer, geometry)
```
but I got an AttributeError
`AttributeError: 'module' object has no attribute 'findWithin2d'`

**Comment by poggenhans** [comment]
Should be fixed with 77ae6722ee1e0c72441409e6143837af7dfa791f.

**Comment by ConstantinB9** [comment]
works perfectly, thanks!
