### ISSUE TITLE
lanelet2_routing presentation isn't rendered

### ISSUE THREAD

**Issue by matthiashh** [fzi-forschungszentrum-informatik/Lanelet2#12]
The lanelet2_routing module readme links to the presentation which isn't rendered correctly on both my machines.

![image](https://user-images.githubusercontent.com/5744579/53658275-9d93ab80-3c58-11e9-9cf8-ff0a1e58c9af.png)

**Comment by poggenhans** [comment]
Seems like htmlpreview no longer does what it once did. I'll fix it by removing the presentation, it didn't contain any information that is not contained in the README.
