### ISSUE TITLE
Any recommends on the GUI interface?

### ISSUE THREAD

**Issue by TonyCMU** [fzi-forschungszentrum-informatik/Lanelet2#13]
I wonder whether there is a simple GUI interface for this package. For example, I can see the routing results or something like that when it works online. Thanks.

**Comment by poggenhans** [comment]
Did you read about the approaches described [here](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/tree/master/lanelet2_routing#3-export-and-debugging-routing-graphs)?

**Comment by TonyCMU** [comment]
Dear Poggenhans,


Thank you so much for your timely replying.
Indeed, I didnot read this section. After I downloaded the package and compiled it sucessfully two days before, I paid much attention to the example code and ignored to read them thoroughly.
Thank you again and sorry for the stupid question. :)


Best regards,
Zhongli Wang






------------------ 原始邮件 ------------------
发件人: "poggenhans"<notifications@github.com>;
发送时间: 2019年3月2日(星期六) 晚上6:25
收件人: "fzi-forschungszentrum-informatik/Lanelet2"<Lanelet2@noreply.github.com>;
抄送: "50095773"<50095773@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [fzi-forschungszentrum-informatik/Lanelet2] Any recommends on theGUI interface? (#13)




Did you read about the approaches described here?

**Comment by matthiashh** [comment]
I have another, somewhat related question:
There wasn't any "live viewing" of data before i left. E.g. for routes one would need to write them to a file and open that one with JOSM.

Are there things on the way? Like ROS messages targeting for RViz or so?

**Comment by poggenhans** [comment]
For displaying stuff in RViz, we have [this](https://github.com/coincar-sim/lanelet_rviz_plugin_ros) unofficial release. But it is still WIP. We will release an official version probably in the next 3-4 months.
