### ISSUE TITLE
Possible RoutingGraph doc inconsistencies

### ISSUE THREAD

**Issue by icolwell-as** [fzi-forschungszentrum-informatik/Lanelet2#134]
I noticed the example code snippets here:
https://github.com/fzi-forschungszentrum-informatik/Lanelet2/tree/master/lanelet2_routing#create-a-routing-graph
Specifically this line:
```
// Create routing graph
RoutingGraphPtr graph = std::make_shared<RoutingGraph>(map, trafficRules /*, costPtrs, routingGraphConf*/);
```
Didn't seem to compile for me, and also doesn't match the example here:
https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_examples/src/06_routing/main.cpp#L39

Also the comment below suggests using "make", but should it suggest using "build" instead?
https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_routing/include/lanelet2_routing/RoutingGraph.h#L418

This is my first time using lanelet routing so please correct me if I'm wrong.
Thanks!

**Comment by poggenhans** [comment]
You were right, the docs were a bit inconsistent there. This should be fixed with 85982c848753998b4114d696e28d8b0e4dee54c3.
