### ISSUE TITLE
Is there a good editor for Lanelet2 to use with pcd map?

### ISSUE THREAD

**Issue by harderthan** [fzi-forschungszentrum-informatik/Lanelet2#139]
Hello. I'm going to learn Lanelet2 recently.
Could you recommend a good editor to make a path with pcd (point cloud data) ?

**Comment by poggenhans** [comment]
I am not sure I understand what you want to achieve. Lanelet2 has nothing to do with point clouds. You are probably confusing a "map" in a broader sense (as a container of spacial data) with "map" in a narrower sense (as something that is used for navigation). A point cloud usually belongs to the first category, a lanelet2 map to the second.

**Comment by kgreenek** [comment]
If you know the transform from your point cloud frame to global gps frame, you could generate openstreetmap tile images that represent your point cloud from a top-down view (https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames). Then you can use those as an imagery source in josm, which has a lanelet2 plugin.

**Comment by harderthan** [comment]
@kgreenek. Really thanks.

Do you know a good way or tools to generate openstreetmap tile images?
