### ISSUE TITLE
lanelet2 validation error

### ISSUE THREAD

**Issue by Shelfcol** [fzi-forschungszentrum-informatik/Lanelet2#140]
Hello , I just built a lanelet map , and I modified all id positive. and I also can visualize it in JOSM, and the longitude and latitude is almost matching the real world. but when I ran  (rosrun lanelet2_validation lanelet2_validate /home/gxf/catkin_ws/src/lanelet_related/osm_edit/src/2020-8-12.osm --lat 31.0281529127 --lon 121.437338508
), many error occurred:
Error: 	- Error parsing primitive 10750: Longitude 121.439d more than 60d from center of UTM zone 31 [general]
Error: 	- Error parsing primitive 10751: Longitude 121.439d more than 60d from center of UTM zone 31 [general]
Error: 	- Error parsing primitive 10752: Longitude 121.439d more than 60d from center of UTM zone 31 [general]
Error: 	- Error parsing primitive 10753: Longitude 121.439d more than 60d from center of UTM zone 31 [general]
Error: 	- Error parsing primitive 10754: Longitude 121.439d more than 60d from center of UTM zone 31 [general]
Error: 	- Error parsing primitive 10755: Longitude 121.439d more than 60d from center of UTM zone 31 [general]
Error: 	- Error parsing primitive 10756: Longitude 121.439d more than 60d from center of UTM zone 31 [general]
Error: 	- Error parsing primitive 10757: Longitude 121.439d more than 60d from center of UTM zone 31 [general]
Error: 	- Error parsing primitive 10758: Longitude 121.439d more than 60d from center of UTM zone 31 [general]
Error: 	- Error parsing primitive 10759: Longitude 121.439d more than 60d from center of UTM zone 31 [general

Just like all the node is not correct.
This is some of my map:
<?xml version="1.0" encoding="UTF-8" ?>
<osm version="0.6" upload="true" generator="opendrive2lanelet">
    <node id="13925" action="modify" visible="true" lat="31.026585048929316" lon="121.43558994482319" version="1" />
    <node id="13924" action="modify" visible="true" lat="31.026585478737257" lon="121.43559516246113" version="1" />
    <node id="13923" action="modify" visible="true" lat="31.026585908544984" lon="121.43560038009906" version="1" />

    <way id="12567" action="modify" visible="true" version="1">
        <nd ref="13925" />
        <nd ref="13924" />
        <nd ref="13923" />
        <nd ref="13922" />
        <nd ref="13921" />
        <nd ref="13920" />
        <nd ref="13919" />
        <nd ref="13918" />
        <nd ref="13917" />
        <nd ref="13916" />
   </way>

 <relation id="12565" action="modify" visible="true" version="1">
        <member type="way" ref="12566" role="right" />
        <member type="way" ref="12567" role="left" />
        <tag k="type" v="lanelet" />
    </relation>
    <relation id="11884" action="modify" visible="true" version="1">
        <member type="way" ref="11885" role="right" />
        <member type="way" ref="12567" role="left" />
        <tag k="type" v="lanelet" />
    </relation>

</osm>

looking forward to your reply. Thank you

**Comment by Shelfcol** [comment]
<node id="13925" action="modify" visible="true" lat="31.026585048929316" lon="121.43558994482319" version="1" />
    <node id="13924" action="modify" visible="true" lat="31.026585478737257" lon="121.43559516246113" version="1" />
    <node id="13923" action="modify" visible="true" lat="31.026585908544984" lon="121.43560038009906" version="1" />
    <node id="13922" action="modify" visible="true" lat="31.026586338352498" lon="121.4356055977371" version="1" />
    <node id="13921" action="modify" visible="true" lat="31.026586768159795" lon="121.43561081527038" version="1" />
    <node id="13920" action="modify" visible="true" lat="31.026587197876697" lon="121.43561603290851" version="1" />
    <node id="13919" action="modify" visible="true" lat="31.02658762768357" lon="121.43562125054666" version="1" />

<relation id="12565" action="modify" visible="true" version="1">
        <member type="way" ref="12566" role="right" />
        <member type="way" ref="12567" role="left" />
        <tag k="type" v="lanelet" />
    </relation>
    <relation id="11884" action="modify" visible="true" version="1">
        <member type="way" ref="11885" role="right" />
        <member type="way" ref="12567" role="left" />
        <tag k="type" v="lanelet" />
    </relation>

**Comment by Shelfcol** [comment]
'''
<node id="13925" action="modify" visible="true" lat="31.026585048929316" lon="121.43558994482319" version="1" />
    <node id="13924" action="modify" visible="true" lat="31.026585478737257" lon="121.43559516246113" version="1" />
    <node id="13923" action="modify" visible="true" lat="31.026585908544984" lon="121.43560038009906" version="1" />
    <node id="13922" action="modify" visible="true" lat="31.026586338352498" lon="121.4356055977371" version="1" />

<relation id="12565" action="modify" visible="true" version="1">
        <member type="way" ref="12566" role="right" />
        <member type="way" ref="12567" role="left" />
        <tag k="type" v="lanelet" />
    </relation>
    <relation id="11884" action="modify" visible="true" version="1">
        <member type="way" ref="11885" role="right" />
        <member type="way" ref="12567" role="left" />
        <tag k="type" v="lanelet" />
    </relation>
    <relation id="11719" action="modify" visible="true" version="1">
        <member type="way" ref="11720" role="right" />
        <member type="way" ref="11721" role="left" />
        <tag k="type" v="lanelet" />
    </relation>
'''

**Comment by Shelfcol** [comment]
node id="13925" action="modify" visible="true" lat="31.026585048929316" lon="121.43558994482319" version="1"
 node id="13924" action="modify" visible="true" lat="31.026585478737257" lon="121.43559516246113" version="1" 
    I just delete <>,or I cannot write the 'node'

**Comment by poggenhans** [comment]
Sorry, I can not reproduce your problem. When I run `lanelet2_validate` with `--lat 31.0281529127 --lon 121.437338508`, the selected UTM zone is 51. Are you sure this is how you ran the program?

**Comment by Shelfcol** [comment]
I have found the error place, it is in&nbsp; lanelet2_interface_ros/launvh/set_lanelet_map.launch, and modify the lat_origin and lon_origin.Thank you all the same



---Original---

**Comment by Shelfcol** [comment]
it's so strange&nbsp; that&nbsp; it runs fine&nbsp; this time,just has some warnings&nbsp; ,&nbsp; &nbsp; linestring 12567 should have a type attribute .&nbsp; But when I run lanelet_rviz_plugin_ros , map cannot plugin correctly, and error says&nbsp; :&nbsp;&nbsp;Error parsing primitive 348: Longitude 121.439d more than 60d from center of UTM zone 32.&nbsp; Should I point the UTM ZONE number directly in somewhere of the code? I will give you my file,&nbsp; if you could check it , I will appreciate it greatly







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fzi-forschungszentrum-informatik/Lanelet2"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月7日(星期五) 下午3:33
收件人:&nbsp;"fzi-forschungszentrum-informatik/Lanelet2"<Lanelet2@noreply.github.com&gt;;
抄送:&nbsp;"Snowm"<740297955@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fzi-forschungszentrum-informatik/Lanelet2] lanelet2 validation error (#140)





 
Sorry, I can not reproduce your problem. When I run lanelet2_validate with --lat 31.0281529127 --lon 121.437338508, the selected UTM zone is 51. Are you sure this is how you ran the program?

**Comment by m-naumann** [comment]
When launching https://github.com/coincar-sim/lanelet2_interface_ros/blob/release/launch/set_lanelet_map.launch you have to set the origin correctly. The values in there are "default" values, these are only valid for the mapping example. I'll remove them soon, to avoid such confusion

**Comment by Shelfcol** [comment]
I&nbsp; think you should just warn somebodyelse in the README.md&nbsp; file, not to remove it.&nbsp;&nbsp;

---Original---

**Comment by m-naumann** [comment]
see https://github.com/coincar-sim/lanelet2_interface_ros/commit/d7891b4578deff67f025edbdeabe87b72a23dfc8
