### ISSUE TITLE
getroute get wrong return for loop scenario

### ISSUE THREAD

**Issue by dufengit** [fzi-forschungszentrum-informatik/Lanelet2#145]
i have a loop map like a Athletic Track, and this map is devided into 4 lanelets, lanelet id is 2000/2001/2002/2003, and connected like 2000->2001->2002->2003->2000, the start lanelet pStart_lanelet is 2002, goal lanelet pGoal_lanelet is 2000. I get route like this:
`    lanelet::Optional<lanelet::routing::Route> route = g_routing_graph->getRoute(pStart_lanelet, pGoal_lanelet, 0);
    if(route){
      for(auto lanelet_el:route->laneletSubmap()->laneletLayer)
      {.....}
`
There should be 3 lanelet in the route->laneletSubmap()->laneletLayer, which should be 2002/2003/2000, but i get all 4 lanelet2 2000/2001/2002/2003 in route->laneletSubmap()->laneletLayer. is this right ?

**Comment by dufengit** [comment]
![cycle_map](https://user-images.githubusercontent.com/34596974/91251340-cc2b0d80-e78d-11ea-8a14-b21fafba2c2c.png)
by excluding  in_edges of pStart_lanelet and out_edges of pGoal_lanelet in the boost::filtered_graph, i get the right return.

**Comment by poggenhans** [comment]
Thanks for reporting, I was able to reproduce the issue in our unittests and am working on a fix.

The solution you proposed works for your case, but it doesn't work if there are lanelets left and right of the start and destination lanelets.

**Comment by dufengit** [comment]
thank you, i just think solution for the one lane scenario, didn't realize multi-lane scenario, waiting for your fix.
