### ISSUE TITLE
possiblePaths including loose ends

### ISSUE THREAD

**Issue by odel4y** [fzi-forschungszentrum-informatik/Lanelet2#146]
Hi!

Similar as in https://github.com/fzi-forschungszentrum-informatik/Lanelet2/issues/144 I have the use case that I would like to find all possible paths starting from a given lanelet. These should include all paths with a given minimum length and those that are shorter but have no lanelet successors (the loose ends of the map). 

Why might the latter case be important? There might for example be an exit of the road leading to a non-public space. The exit is only mapped with a short lanelet without successors. Here, it is important to know that this exit is one of the possible maneuver alternatives for the vehicle even though it does not fulfill the length criterion.

From my understanding this can currently only be achieved by calling possiblePaths with several different given lengths and combining the results. Instead it would be nice to provide a boolean argument to possiblePaths, that states whether loose ends should be included, even if they do not fulfill the criterion.

Implementation-wise, I believe that removing the second condition in this line should solve this task: https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/503a6519066d444742b3ac7caa211fd37d173868/lanelet2_routing/src/RoutingGraph.cpp#L234 
Would this make a sensible addition to the framework?

**Comment by poggenhans** [comment]
We'll think about a solution for that. This behavior has been requested a couple of times, but extending the list of parameters passed to possiblePaths would make it too complex. Maybe we will add another function that gets an `Options` object instead.

**Comment by poggenhans** [comment]
Introduced with fb249d98153b38f79c6856ffad58ae71a6359d2e and fcf5a1aca31aa6b375341f6c9aaf1c33c792fb9d
