### ISSUE TITLE
adjacent lanelet problem

### ISSUE THREAD

**Issue by dufengit** [fzi-forschungszentrum-informatik/Lanelet2#147]
I need to get adjacent lane relation of 2 lanelets with the opposite direction, but Optional<ConstLanelet> RoutingGraph::adjacentLeft(const ConstLanelet& lanelet) in src/lanelet2/lanelet2_routing/src/RoutingGraph.cpp get nothing for this scenario, the scenario is like pic below, i want to get adjacentLeft lanelet of laneletB, which should be laneletA, but get nothing by function adjacentLeft.
![adjacent_lanelet](https://user-images.githubusercontent.com/34596974/91587227-0ca2ab00-e989-11ea-9422-ce39f2b41d02.png)
I checked, and find function leftOf is used when build boost::graph
template <typename Lanelet1T, typename Lanelet2T>
IfLL<Lanelet1T, IfLL<Lanelet2T, bool>> leftOf(const Lanelet1T& left, const Lanelet2T& right);
it judge the left relation use:
left.rightBound() == right.leftBound()
which only work for lanelet whose direction is the same.
for opposite direction adjacent lanelet,should be checked by this condition:
left.leftBound().invert() == right.leftBound()

Is return nothing specification for this scenario, or there should be return?

**Comment by dufengit** [comment]
So for overtake maneuver using opposite lane(yellow dashed line), there is no routing method? or this situation should be include in trafficRules ?

**Comment by poggenhans** [comment]
Traffic rules are meant to be a customization point for users where they can implement their own behavior for the routing graph. For overtaking, I would suggest to create special overtaking traffic rules and use the graph created from them to plan these maneuvers.

**Comment by dufengit** [comment]
Ok, thank you very much for your suggestion.

**Comment by icolwell-as** [comment]
I just came across this today too, it seems like a common use case (#100). Would it make sense to add an official `opposing` relation?
If `adjacent left/right` are available, but not traversable, then it shouldn't be much different to add `opposing` right? 
I don't know all the details behind the routing graph though.

**Comment by poggenhans** [comment]
Yes, could definitively make sense. Also for applications like overtaking using the opposing lane. Basically we would need four new different opposing relations (left/right, lane change for overtaking possible/not possible). I think we even have the information about opposing lanelets at some point when we create the graph, but we discard them after finding out that they are neither adjacent nor left/right.

Even though it should be quite straightforward to add this, it would require resources that we currently don't have, tbh. Unless there is an internal use case that makes it necessary for us. If you need this, I would suggest you implement it yourself.
