### ISSUE TITLE
[Question] findWithin2d, but for an area?

### ISSUE THREAD

**Issue by vadeshah** [fzi-forschungszentrum-informatik/Lanelet2#148]
I have a vehicle trajectory, given as a series of (x, y) coordinates of the vehicle's center, that runs through an .osm map. I've been using Lanelet2's findWithin2d feature to identify which lanelets the **exact center** of the vehicle lies in. However, the vehicle also has a width, length, and yaw angle, and can thus be represented by a rectangle instead of just its centerpoint. Is there any built-in function in Lanelet2 that I can use to find all of the lanelets that any point within the **vehicle's area** (defined by the aforementioned rectangle) lies in? If not, any recommendations on how to do this? I could define a series of points that represent its boundary and run findWithin2d on all of those, but I wanted to see if there was a cleaner solution.

Thanks in advance!

**Comment by m-naumann** [comment]
You could have a look at https://github.com/coincar-sim/lanelet2_matching, should be doing what you intend to

**Comment by vadeshah** [comment]
Does this package have any Python functionality? Currently, I've been relying on Lanelet2's Python bindings.

**Comment by m-naumann** [comment]
Not yet, but will be added soon

**Comment by m-naumann** [comment]
Please have a look at https://github.com/coincar-sim/lanelet2_matching/tree/add_python_api

**Comment by vadeshah** [comment]
Amazing! I'll try it out and let you know how it goes.

**Comment by m-naumann** [comment]
It's merged to master meanwhile: https://github.com/coincar-sim/lanelet2_matching
