### ISSUE TITLE
Failed     << lanelet2_python:make                  [ Exited with code 2 ]

### ISSUE THREAD

**Issue by dinesh3367** [fzi-forschungszentrum-informatik/Lanelet2#149]
I am getting the below error message while trying to do  a catkin build in ubuntu 18.04 pc

Failed     << lanelet2_python:make                  [ Exited with code 2 ]
Failed    <<< lanelet2_python                       [ 9 minutes and 31.1 seconds ]
Abandoned <<< lanelet2_validation                   [ Unrelated job failed ]
Abandoned <<< lanelet2                              [ Unrelated job failed ]
Abandoned <<< lanelet2_examples                     [ Unrelated job failed ]
[build] Summary: 7 of 11 packages succeeded.
[build]   Ignored:   None.
[build]   Warnings:  None.
[build]   Abandoned: 3 packages were abandoned.
[build]   Failed:    1 packages failed.
[build] Runtime: 15 minutes and 45.3 seconds total.
[build] Note: Workspace packages have changed, please re-source setup files to use them.
cat@cat-VirtualBox:~/catkin_ws$ cat /home/cat/catkin_ws/logs/lanelet2_python/build.make.000.log
Scanning dependencies of target _catkin_empty_exported_target
[  0%] Built target _catkin_empty_exported_target
Scanning dependencies of target lanelet2_python-lanelet2-projection-pyapi
[  8%] Building CXX object CMakeFiles/lanelet2_python-lanelet2-projection-pyapi.dir/python_api/projection.cpp.o
[ 16%] Linking CXX shared library /home/cat/catkin_ws/devel/.private/lanelet2_python/lib/python2.7/dist-packages/lanelet2/projection.so
[ 16%] Built target lanelet2_python-lanelet2-projection-pyapi
Scanning dependencies of target lanelet2_python-lanelet2-traffic_rules-pyapi
[ 25%] Building CXX object CMakeFiles/lanelet2_python-lanelet2-traffic_rules-pyapi.dir/python_api/traffic_rules.cpp.o
[ 33%] Linking CXX shared library /home/cat/catkin_ws/devel/.private/lanelet2_python/lib/python2.7/dist-packages/lanelet2/traffic_rules.so
[ 33%] Built target lanelet2_python-lanelet2-traffic_rules-pyapi
Scanning dependencies of target lanelet2_python-lanelet2-core-pyapi
[ 41%] Building CXX object CMakeFiles/lanelet2_python-lanelet2-core-pyapi.dir/python_api/core.cpp.o
[ 50%] Linking CXX shared library /home/cat/catkin_ws/devel/.private/lanelet2_python/lib/python2.7/dist-packages/lanelet2/core.so
[ 50%] Built target lanelet2_python-lanelet2-core-pyapi
Scanning dependencies of target lanelet2_python-lanelet2-geometry-pyapi
[ 58%] Building CXX object CMakeFiles/lanelet2_python-lanelet2-geometry-pyapi.dir/python_api/geometry.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
CMakeFiles/lanelet2_python-lanelet2-geometry-pyapi.dir/build.make:62: recipe for target 'CMakeFiles/lanelet2_python-lanelet2-geometry-pyapi.dir/python_api/geometry.cpp.o' failed
make[2]: *** [CMakeFiles/lanelet2_python-lanelet2-geometry-pyapi.dir/python_api/geometry.cpp.o] Error 4
CMakeFiles/Makefile2:544: recipe for target 'CMakeFiles/lanelet2_python-lanelet2-geometry-pyapi.dir/all' failed
Makefile:140: recipe for target 'all' failed
make[1]: *** [CMakeFiles/lanelet2_python-lanelet2-geometry-pyapi.dir/all] Error 2
make: *** [all] Error 2
![catkin](https://user-images.githubusercontent.com/31798603/92296994-3004c180-ef58-11ea-85e2-663232c38ab5.PNG)

**Comment by m-naumann** [comment]
Maybe you don't have enough RAM? You can try `catkin build -j1`

**Comment by dinesh3367** [comment]
I did manage to build it now and i don't have any issues now.
Between i didn't use the option '-j1' with catkin build
Thanks for your response
