### ISSUE TITLE
Picking specific line segment from the lanelet map (OSM)

### ISSUE THREAD

**Issue by ajay1606** [fzi-forschungszentrum-informatik/Lanelet2#151]
Hello, thank you so much lanelet2 opensource library. I am trying to get the specific line segment id and its lat and long values based on the current GPS position. Is there any way that I can get that information robustly.

Really appreciate your help.
Ajay

**Comment by poggenhans** [comment]
In our examples you can find several ways how to determine the closest objects to a given position or search area: https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_examples/src/03_lanelet_map/main.cpp#L93

Before you can use this with a GPS point, you have to transform that into local coordinates using the projector that you used for loading the map. There is also an example about that: https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_examples/src/04_reading_and_writing/main.cpp#L61
