### ISSUE TITLE
Circular dependency warning in JOSM

### ISSUE THREAD

**Issue by simon0302** [fzi-forschungszentrum-informatik/Lanelet2#155]
<img width="809" alt="Screen Shot 2020-10-25 at 3 14 23 PM" src="https://user-images.githubusercontent.com/23201606/97370689-c96f9600-186c-11eb-8151-7a172b22e822.png">

This warning for circular dependency pops up for regulatory elements (right_of_way and all_way_stops)

**Comment by icolwell-as** [comment]
If you have a recent version of JOSM go to "Edit" -> "Preferences" -> "Advanced Preferences" (bottom tab with wrench)
Then search for `validator.relation.allow.complex.dependency`, if that preference comes up, set it to true, if it doesn't come up, downgrade to an older version of JOSM.

See here for more details:
https://josm.openstreetmap.de/ticket/19312#comment:21

**Comment by simon0302** [comment]
Thank you, changing this setting worked!
