### ISSUE TITLE
/bin/sh: 1: rosrun: not found

### ISSUE THREAD

**Issue by 110dazhi** [fzi-forschungszentrum-informatik/Lanelet2#157]
Hello，
![ERROR](https://user-images.githubusercontent.com/57225932/97859972-a24c1500-1d01-11eb-9615-510cdd1f0086.png)
I installed lanelet2 in docker, and then I connected the professional version of pycharm to docker, and then I ran E:\Myproject\Lanelet2\lanelet2_examples\scripts\tutorial.py with docker started. At first, it said that the module lanelet2 was missing, but After I added the environment variable, it can run normally without error. But then when I want to run E:\Myproject\Lanelet2\lanelet2_examples\test\test_examples.py again, the program keeps reporting an error: /bin/sh: 1: rosrun: not found.

I have tried to change python2.7 to python3, and also tried to add ENV in dockerfile, but this error will not disappear. However, when I run [python test_examples.py] in powershell, it is normal and no error occurs. So how can I solve this problem?

**Comment by poggenhans** [comment]
How exactly did you build this docker image? The paths are not as I would expect them from our dockerfile.

Clearly you did not source the ros environment, so all ROS commands are not available to you. Usually this is done by running `source /opt/ros/<distro>/setup.bash`, where disto is the name of the ROS distro you have installed.

**Comment by 110dazhi** [comment]
Hi,I used the following steps to install the image.
1. Install docker from https://hub.docker.com/editions/community/docker-ce-desktop-windows/
2. Clone lanelet2 git in PowerShell (to open PowerShell search for it)
$ git clone https://github.com/fzi-forschungszentrum-informatik/lanelet2.git
$ cd ./lanelet2/
3.Build docker via:
$ docker build -t lanelet2 .
In powershell, the program can be run well and bin/sh:1:rosrun:not found does not appear.
![Powershell](https://user-images.githubusercontent.com/57225932/97876670-75592b80-1d1c-11eb-8e33-85d38f691b18.png)

This kind of error appears when I use pycharm and docker to connect：
I think this is a bug between pycharm and docker under windows
![not found](https://user-images.githubusercontent.com/57225932/97878097-71c6a400-1d1e-11eb-8872-362944371c12.png)

**Comment by poggenhans** [comment]
In that case, I suppose pycharm is indeed lacking some environment variables that are usually set when you enter the docker container by sourcing `.bashrc`.

You can probably do this manually, e.g. when you instead run `source /home/developer/.bashrc && python -u /home/developer/workspace/src/lanelet2/lanelet2_examples/test/test_examples.py`. If pycharm offers a way to source this file automatically, that would work too.
