### ISSUE TITLE
findUsages doesn't return all corresponding elements

### ISSUE THREAD

**Issue by JoScha515** [fzi-forschungszentrum-informatik/Lanelet2#158]
I want to use the function findUsages() with the area layer: 
`rel_areas = map.areaLayer.findUsages(linestr)`

What i expect is to get all areas which refer to that linestring (e.g. one linestring which is part of to areas -> those two areas should be returned).

Somehow i don't get all areas which use this linestring:
A linestring is used by two areas and i get only one of those areas returned by the function.
In another case the linestring is used by four areas but the function returns only to of those areas.
When i check the map with josm all references appear.

Is there an error or a misunderstanding of this function from me?

**Comment by poggenhans** [comment]
I suspect this is because the orientation matters. `map.areaLayer.findUsages(linestr.invert())` gives you different results than searching with an uninverted linestring.

**Comment by JoScha515** [comment]
OK, I didn't know that.
It works and i get all related areas when i do it with the linestring and the inverted linestring.
Thank you very much!
