### ISSUE TITLE
RuntimeError: Errors occured while writing lanelet map:

### ISSUE THREAD

**Issue by dinesh3367** [fzi-forschungszentrum-informatik/Lanelet2#159]
I am getting the following error 
![image](https://user-images.githubusercontent.com/31798603/98853591-5e82a980-247f-11eb-968b-625406b27d7d.png)

while trying to write the map generated from the shortest route query

```
 graph = lanelet2.routing.RoutingGraph(map, traffic_rules)
 route=graph.getRoute(start_lanelet, end_lanelet,0,1)
 laneletSubmap = route.laneletSubmap()
 map = laneletSubmap.laneletMap()

 map.add(LineString3d(getId(),centerline_points))  

 path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'output_.osm')
 lanelet2.io.write(path, map, proj)
```

it is complaining about the way of the centerline nodes are missing in the final output. PLease let me know if i am missing something here.
Thanks

**Comment by dinesh3367** [comment]
looks like the following code
```
laneletSubmap = route.laneletSubmap()
 map = laneletSubmap.laneletMap()

```
couldn't extract the ''centerline'''nodes way id which was originally available in the lanlet relation definition

**Comment by poggenhans** [comment]
Looks like our map building algorithm is ignoring customized centerlines. I'll look into it. Shouldn't be too hard to fix.

**Comment by dinesh3367** [comment]
Thanks for acknowledging that. Would you let us notified once you fix the issue ?

**Comment by dinesh3367** [comment]
Thanks guys the issue is sorted out now.
