### ISSUE TITLE
Create left and right boundaries with the help of Centerline points

### ISSUE THREAD

**Issue by dinesh3367** [fzi-forschungszentrum-informatik/Lanelet2#161]
Does the lanelet2 team have any plans of creating left and right boundaries at a specified width from the given Centerline points ??. 

I am raising this point as we get the Centerline points recorded from a rover for our current site.

Hope this helps

**Comment by poggenhans** [comment]
You may want to look into `lanelet::geometry::offset` in `lanelet2_core/geometry/LineString.h`. It returns a `BasicLineString2d` left or right of the input linestring with a fixed distance. You could use this to construct a Lanelet.
