### ISSUE TITLE
Regulatory Element parameters cannot be 2D?

### ISSUE THREAD

**Issue by rowandempster** [fzi-forschungszentrum-informatik/Lanelet2#165]
Looking at the possible variants of `RuleParameters`, it seems like the 2D version of the primitives are explicitly disallowed: https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_core/include/lanelet2_core/primitives/RegulatoryElement.h#L90 

This does not impose a technical limitation perse (since 2D is a subset of 3D), but if I am working with 2D data I would like to make that clear by using the 2D designated classes. Why was this implementation choice made to disallow that?

**Comment by poggenhans** [comment]
The line you are referring to is just an implementation detail. For lanelet2, we assume that everything is in 3d, but you can always get a 2d view if you need it. Its fine if you don't need the third dimension, but it will always be there. So if you store a parameter in 3d, you should also be able to retrieve it, even if you ask for a 2d type and vice versa. This wouldn't be possible if the variant you are referring to would also include the 2d types.

That doesn't mean we "disallow" 2d. Instead, it is just converted on the fly. E.g. you can still do `LineStrings2d linestrings = regelem.getParameters<LineString2d>(Refers);` and it will give you all linestrings of that role, converted to 2d.

**Comment by rowandempster** [comment]
Makes sense @poggenhans, map data has to be 3D. The 2D classes just serve as views.
