### ISSUE TITLE
Obtaining Road Boundary Points - Given Lanelet

### ISSUE THREAD

**Issue by vimalrajayyappan** [fzi-forschungszentrum-informatik/Lanelet2#169]
Kindly help me in getting the road border information on providing a particular lanelet. Also, help me in knowing the way the XML is being parsed. I tried analyzing the code.

**Comment by poggenhans** [comment]
We use pugixml for parsing the XML. Look [here](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_io/src/OsmHandlerLoad.cpp) if you want to know the details.

For extracting the boundary from a lanelet have a look at our [examples](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_examples/src/01_dealing_with_lanelet_primitives/main.cpp#L247).

**Comment by vimalrajayyappan** [comment]
Thanks :)
