### ISSUE TITLE
[question] position of road signs

### ISSUE THREAD

**Issue by amastrobera** [fzi-forschungszentrum-informatik/Lanelet2#170]
Hi guys,

how would you encode a road-sign, and how would you define its position with respect to the reference lanelet ? 

Angelo

**Comment by poggenhans** [comment]
I don't think we specified this anywhere. Usually we either encode them as a linestring where the first point is the leftmost edge of the sign and the last the rightmost edge (useful when using aerial imagery) or with the shape as clockwise polygon (useful when creating maps from sensor data).

**Comment by icolwell-as** [comment]
https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_core/doc/LinestringTagging.md#traffic-signs
