### ISSUE TITLE
create lanelet map with UAV imagery

### ISSUE THREAD

**Issue by ZhangHongjuan** [fzi-forschungszentrum-informatik/Lanelet2#171]
Hi,

thanks for your work, really awesome. I found that you made lanelet map using satellite imagery. I am wondering if I could use UAV imagery to make lanelet map, as UAV imagery has higher resolution. Looking for your answer.

**Comment by poggenhans** [comment]
You can use whatever kind of imagery you like. You just have to make JOSM display it if you want to to do the labelling of the map in there.

**Comment by m-naumann** [comment]
I can recommend piclayer: https://wiki.openstreetmap.org/wiki/JOSM/Plugins/PicLayer
