### ISSUE TITLE
Lanelet2:  Extracting the length of each lanelet

### ISSUE THREAD

**Issue by prajwalainapur** [fzi-forschungszentrum-informatik/Lanelet2#172]
I am working on an application using lanelet2 maps which requires to extract the length of each lanelet. The crude approach is to calculate euclidean distance between each point in the center line of the given lanelet. Is there any other better way to implement the same, maybe from the annotation end as well such as including it as an attribute to the lanelet. Please help.

**Comment by poggenhans** [comment]
What is bad about calculating the ecuclidean distance of the points on the centerline? There is also a `lanelet::geometry::length2d(mylanelet)` but it does exactly the same thing that you describe.

**Comment by prajwalainapur** [comment]
Given the current lanelet id and the global path, i am looking to query the list of all regulatory elements in the next 'x meters' from the current lanelet along the path. So doing this in real time by calculating distance between each point pair along the center line is significantly time taking. Can we have something like, length of a lanelet imputed as part of the lanelet attributes, created during the map building phase itself. So that if we just take out the list of lanelet id's  along my global path, the distance can easily be calculated with little to no computation load for real time systems?

**Comment by orzechow** [comment]
Recomputing the lanelet lengths is not optimal, you are right. But if you have a lanelet route, why not use bounding box search on a route submap to efficiently find the surrounding regulatory elements, thus reducing the number of regulatory elements that have to be checked:

```cpp
auto nearRegulatoryElements = route.laneletSubmap()->regulatoryElementLayer.search(someBoundingBox);
```

See 
[Route::laneletSubmap()](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_routing/include/lanelet2_routing/Route.h#L81), [LaneletMapLayers::regulatoryElementLayer](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_core/include/lanelet2_core/LaneletMap.h#L355) and [PrimitiveLayer::search()](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_core/include/lanelet2_core/LaneletMap.h#L172).

Then it is only a matter of reordering and transforming to arc coordinates with e.g. [lanelet::geometry::toArcCoordinates()](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/e774b8701a9d0e0c743e907d92fcbab03528e5ef/lanelet2_core/include/lanelet2_core/geometry/LineString.h#L122). Still you'll probably need the length of lanelets along the route though.

You could also have a look into [lanelet::geometry::approximatedLength2d()](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/e774b8701a9d0e0c743e907d92fcbab03528e5ef/lanelet2_core/include/lanelet2_core/geometry/Lanelet.h#L22).
