### ISSUE TITLE
Provision to create Custom Regulatory Elements

### ISSUE THREAD

**Issue by prajwalainapur** [fzi-forschungszentrum-informatik/Lanelet2#173]
I went through the lanelet2 package and i believe that we can create custom elements by altering the source code. However, i wanted to cross check if the package provides any provisions to create custom regulatory elements in a easier way. Any help or information regarding this is highly appreciated.

**Comment by poggenhans** [comment]
There should be no need to alter the source code. Just implement them in your own project. The regulatory elements provided in BasicRegulatoryElements.h have no special role compared to something that you implement yourself. There is a small section in the [docs](http://docs.ros.org/en/noetic/api/lanelet2_core/html/doxygen/group__RegulatoryElementPrimitives.html) about how to add new regulatory elements.

**Comment by prajwalainapur** [comment]
Thank you @poggenhans for guiding me to the document. This is what i was looking for.
