### ISSUE TITLE
how to extract x,y coordinates from a Linestring?

### ISSUE THREAD

**Issue by miropipa** [fzi-forschungszentrum-informatik/Lanelet2#179]
I am trying to write the x,y coordinates of the nodes forming the centerline of a lanelet to a txt.file. I understand that i can use a combination of  arcCoordinates and interpolatedPointAtDistance to achieve this, but I wonder if there is more direct approach to publishing the x,y coordinates of the centerline.

**Comment by poggenhans** [comment]
You can simply iterate the centerline linestring. E.g. in python:
```python
for point in lanelet.centerline:
    file.write("{}, {}\n".format(point.x, point.y))
```
and in C++:
```c++
for(const ConstPoint3d& point : lanelet.centerline())
    file << point.x() << ", " << point.y() << "\n";
```

**Comment by miropipa** [comment]
thank you so
