### ISSUE TITLE
About OSM format specifiacation

### ISSUE THREAD

**Issue by DmitryRedin** [fzi-forschungszentrum-informatik/Lanelet2#180]
Hello.

Where can I find the specification(information about all tags, objects and xml-structure) of the OSM / lanelet2 format?

**Comment by miropipa** [comment]
You can find such information here: 1) https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_maps/README.md
2) https://wiki.openstreetmap.org/wiki/OSM_XML

**Comment by poggenhans** [comment]
Closing, this seems to have been resolved...
