### ISSUE TITLE
Search primitives based on pre defined bounding box

### ISSUE THREAD

**Issue by ajay1606** [fzi-forschungszentrum-informatik/Lanelet2#183]
Hello Everyone, Trying to find the closest primitives to the current GPS location using the following method provided with 
Lanelet 

Sample code:
```
  // finally we can get primitives using a search region (this also runs on the bounding boxes):
  Lanelets inRegion = laneletMap.laneletLayer.search(BoundingBox2d(BasicPoint2d(0, 0), BasicPoint2d(10, 10)));
  assert(!inRegion.empty());  // inRegion contains all lanelets whose bounding boxes intersect with the query
```
Currently using like this below:
```
lanelet::BasicPoint2d start_point(gps_point.lat, gps_point.lon);
lanelet::BasicPoint2d end_point(gps_point.lat-10, gps_point.lon-10);
Lanelets inRegion = laneletMap.laneletLayer.search(BoundingBox2d(start_point, end_point));
assert(!inRegion.empty());  // inRegion contains all lanelets whose bounding boxes intersect with the query
```

Currently, I have tried with varying end_point range, but still unable to intersect Lanelet primitives, getting inRegion size '0'. Please, anyone, suggest me where I am doing wrong?

Help much appreciated.

**Comment by m-naumann** [comment]
I guess you confused metric x/y coordinates, in which lanelet2 is operating, with lat/lon coordinates. You have to project your lat/lon position to metric coordinates first. See 
- https://github.com/fzi-forschungszentrum-informatik/Lanelet2/tree/master/lanelet2_projection#need-for-projections and
- https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_projection/doc/Map_Projections_Coordinate_Systems.md 

for details.

**Comment by ajay1606** [comment]
@m-naumann Thanks it's working now.
