### ISSUE TITLE
Retrieve 3D position information stored in Points  

### ISSUE THREAD

**Issue by ajay1606** [fzi-forschungszentrum-informatik/Lanelet2#184]
Hello, 
As i understand, Points are composed of ID, 3D coordinates and attributes, and are the only elements that store actual position information. The ID must be unique. The other basic elements are directly or indirectly composed of points.

Am trying to fetch information stored in Points Datastructure Lanelet using the following function;
Using `lanelet_map_ptr_->laneletLayer.search(lanelet::BoundingBox2d(search_point, search_point2)); ` am able to get point ids as like below

```
 Lanelet Left :[id: 17391879 point ids: 17383600, 17391881]
 Lanelet Right :[id: 17391978 point ids: 17383604, 17383602]
```
Further, how can I get lat&lon information stored in the points with ids? Could anyone please suggest. 

Regards,
Ajay

**Comment by poggenhans** [comment]
as already disussed in #183, everything in lanelet2 is in a metric coordinates. [Our examples](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_examples/src/01_dealing_with_lanelet_primitives/main.cpp) should cover how to get the local x/y coordinates of points within a lanelet.

If you want lat/lon coordinates, you have to transform these points into  `GPSPoints` using the projection. That is covered [in the examples](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_examples/src/04_reading_and_writing/main.cpp#L61) too.

**Comment by ajay1606** [comment]
@poggenhans Thanks so much for your response. Here, the problem is not about the local_x/local_y or lat/long. Instead am trying to retrieve position information (local_x/local_y,  lat/long) in the laneletLayer.  Here with Step by Step code and my question regarding the position retriving!

```
//Get nearest lanelet
std::vector<std::pair<double, lanelet::Lanelet>> nearest_lanelets = lanelet::geometry::findNearest(lanelet_map_ptr_->laneletLayer, search_point, 4);

//Iterating each lanelet in nearest_lanelet and get attributes associated with each lanelet.
for (const auto & lanelet : nearest_lanelets) 
```
Each lanelet contains following :
- id: Int  
- left_bound: LineString
- right_bound: LineString
- center_line: LineString
- attibutes: List<Attribute>
- regulatory_element: List<RegulatoryElement>

Using `lanelet.second.leftBound()` able to get following id:
```
 Lanelet Left :[id: 17391879 point ids: 17383600, 17391881]
 Lanelet Right :[id: 17391978 point ids: 17383604, 17383602]
```
So my question is here, How to get position data associated with the point ids. 
Is there any function or code, where i can access this point ids to get position ?

Your help much appreciated. 

Kind Regards,
AJay
