### ISSUE TITLE
Lanelet2 parsing returns Lanelet ID which is not exists  

### ISSUE THREAD

**Issue by ajay1606** [fzi-forschungszentrum-informatik/Lanelet2#187]
Hello,
Appreciate your kind help in understanding Lanelet information retrieval. 
While parsing Lanelet for retrieving POINT information at few instances getting Lanelet ID, which does not exist in the .osm file. 

**Scenario: Retrieving lanelets near to vehicle position.**
![image](https://user-images.githubusercontent.com/29722843/114497187-852a5380-9c5c-11eb-8142-99b1f2923a95.png)
```
//Gets lanelets in defined region
lanelet::Lanelets inRegion =lanelet_map_ptr_->laneletLayer.search(lanelet::BoundingBox2d(search_point, search_point+1)); 
//Parsing lanelets returned by the search
for (const auto & laneletsIn : inRegion) 
//Looking for only center line()
 for(size_t i=0; i<laneletsIn.centerline().size(); i++)
```

**Lanelets in OSM file:**
![image](https://user-images.githubusercontent.com/29722843/114489007-50fb6680-9c4d-11eb-99f4-07b552a447b4.png)

**Expected result:**
Get all the lanelets (Centerline) with in the Region of bounding box:
  [id: 189968504 point ids: 189968505, 189968506, 189968507, 189968508, 189968509]
 [id: 189977162 point ids: 189968505, 189977164, 189977165, 189977166, 189977167, 189977168, 189977169, 189977170, 189968059]
 [id: 189972472 point ids: 189969165, 189972474, 189972475, 189968509]
 [id: 189968504 point ids: 189968505, 189968506, 189968507, 189968508, 189968509]
[id: 189977162 point ids: 189968505, 189977164, 189977165, 189977166, 189977167, 189977168, 189977169, 189977170, 189968059]

**Actual result:**
Getting some lanelet, which does not exist in the OSM file.
  [id: 189968504 point ids: 189968505, 189968506, 189968507, 189968508, 189968509]
 [id: 189977162 point ids: 189968505, 189977164, 189977165, 189977166, 189977167, 189977168, 189977169, 189977170, 189968059]
**[id: 189980510 point ids: 189980511, 189980512, 189980513, 189980514]**
 [id: 189972472 point ids: 189969165, 189972474, 189972475, 189968509]
 [id: 189968504 point ids: 189968505, 189968506, 189968507, 189968508, 189968509]
[id: 189977162 point ids: 189968505, 189977164, 189977165, 189977166, 189977167, 189977168, 189977169, 189977170, 189968059]

Along with the existing Lanelet ID's, some additional Lanelet ID's appearing in the search function, though its actually not exists in the OSM file. Also I did search for this ID in the lanelet, but it does not exist. 

![image](https://user-images.githubusercontent.com/29722843/114498101-717fec80-9c5e-11eb-816f-4c09ca82fcf5.png)

My question:

Is lanelet OSM file parser generate seperate ID's along with the ID already exists in the OSM file ?

Regards,
Ajay

**Comment by m-naumann** [comment]
What you are visualizing is the ID of the centerline if I'm not mistaken, not the ID of the lanelet. The IDs that are unexpected look newly created, since they are ascending. Maybe look at the lanelet IDs to trace the problem, or provide more information here (map and code).

**Comment by ajay1606** [comment]
@m-naumannThank you so much for your response.
I tried to trace the newly created Lanelet ID in the OSM file, as i showed in this image, I could trace all the IDs that exist in the OSM file, but not the newly created ID.
![image](https://user-images.githubusercontent.com/29722843/114796956-13254c00-9dcd-11eb-9ce9-c5ba39e7d433.png)

If possible, may I share Lanelet map with you personally? Appreciate your kind understanding.

Regards,
Ajay

**Comment by poggenhans** [comment]
Well without at least the full code its hard to say what your problem is. One way I can think of is if you are adding the centerlines of the lanelets to a `LaneletMap`. Centerlines and the points they are composed of are usually generated automatically with an id of 0 (indicating they are artificial). When you add them to a map, lanelet2 assigns them an id, since they are now "materializing" to a no longer an artificial thing. And this could be the id that you are seeing.

But in general, you should be aware that lanelets and their centerline are different entities and also have different ids. The statement is correct that usually lanelet2 returns centerlines that didn't exist before (because it computed them) but it doesn't invent lanelets that didn't exist before.

**Comment by ajay1606** [comment]
@poggenhans Thank you so much for your response, well, if this is the case,  lanelet2 returns **centerline** that didn't exist before then fine. I understand this as common behavior.
