### ISSUE TITLE
06_routing--error

### ISSUE THREAD

**Issue by leiyubiao** [fzi-forschungszentrum-informatik/Lanelet2#188]
When I run the executable file in example file, it occurs problem as following shows. How can I deal with it?

________________________________________________________________________________________________________
./06_routing: symbol lookup error: ./06_routing: undefined symbol: _ZN7lanelet7routing21RoutingCostTravelTime10travelTimeERKNS_13traffic_rules12TrafficRulesERKNS_9ConstAreaE

**Comment by poggenhans** [comment]
Looks like something went wrong when linking the lanelet2 libraries. But without background information, we cannot help you. What system are you running? How did you build lanelet2? How did you run it? Did you try reproducing the error somewhere else?

**Comment by leiyubiao** [comment]
I have solved the problem.  I installed the lanelet2 by "sudo apt-get install lanelet2",  so when I installed the lanelet2 by source code, it happend the error. I use "sudo apt-get remove lanelet2*"
to solve the problem.
