### ISSUE TITLE
How to load lanelet file in Postgis?

### ISSUE THREAD

**Issue by arvindkyutech** [fzi-forschungszentrum-informatik/Lanelet2#190]
I was trying osm2pgsql to load lanelet file in PostGIS, it does not work perfectly for the lanelet case as it has extra tags. Do we have any method for this in the lanelet2 library to manage PostGIS?

**Comment by poggenhans** [comment]
Sorry, we are not using Postgis. I suppose it would be possible to register a `lanelet2_io` compatible reader/writer that translates the lanelet2 representation and tags to something postgis can work with, but this is no support for this in lanelet2 (and we dont plan to add it).

**Comment by arvindkyutech** [comment]
Thank you so much for your help.
