### ISSUE TITLE
[lanelet2_python] ConstPoint2d doesn't have basicPoint method

### ISSUE THREAD

**Issue by mkolodziejczyk-piap** [fzi-forschungszentrum-informatik/Lanelet2#192]
Hi,
Just like in title. Asking mostly if this is by omission or intentional

https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/dd447838552a860718789912917b1a7424b0c520/lanelet2_python/python_api/core.cpp#L558-L580

Regards,

**Comment by poggenhans** [comment]
Rather an omission. `ConstPoint2d` is very rarely used in the python interface and was added a bit later than the rest, so we probably simply forgot to add the method. I'll prepare a fix for this.
