### ISSUE TITLE
[Question] Routing with a small scale roads

### ISSUE THREAD

**Issue by AlexKaravaev** [fzi-forschungszentrum-informatik/Lanelet2#195]
Hi ! I am working on a project with a small scale self driving rc cars and I want to research lanelet2 for that. Lane width for will be around 50cm. I had composed .osm file and was trying to run routing for it, but I had no success. Moreover, when I visualize debug routing graph, it will return strange results. 

I wanted to ask, if it's some problem with my .osm file or routing simple not suited for such use-scenario? I compared the .osm file I have with some test ones in res folder in lanelet2_routing and for me they have looked identical, so I don't know what's the problem

# Files
* [osm file](https://drive.google.com/file/d/1mGzYB5__VdYOZCU4Jr8J_eGY50fJKTEG/view?usp=sharing)
* [osm debug route graph](https://drive.google.com/file/d/1qNWoVMpe35GcSpAR2zI5O5RcbraVuYfU/view?usp=sharing)

**Comment by dymons** [comment]
Hello. I found the following errors in the map:
- The direction of the Lanelets is incorrect
- Lanelets are not connected correctly
- In one of your Lanelets, you had two right-hand borders indicated

I corrected all these errors, and you can see the result of the corrections in the attached file.
[map.osm](https://drive.google.com/file/d/1NWLnSNBGNn869e7Cm4fj4O7GHXPN97ed/view?usp=sharing)

Map verification passed! :)
[Video](https://www.youtube.com/watch?v=tMtaam7lYXk)

**Comment by AlexKaravaev** [comment]
@dymons Thank you very much! It was enough off course to just point at errors, but I can not be more thankful for correcting the errors and showing the actual routing happening!)
