### ISSUE TITLE
C++14 requirement not in CMakeLists.txt

### ISSUE THREAD

**Issue by james-ward** [fzi-forschungszentrum-informatik/Lanelet2#2]
Catkin builds using ROS Melodic are fine, but earlier versions fail due to the default C++ standard not being C++14.
Adding the flag in `CMakeLists.txt` would fix this.

**Comment by james-ward** [comment]
Thanks. That might be the problem.

The first error is:
`In file included from /home/james/research/zio/src/lanelet2/lanelet2_validation/include/lanelet2_validation/validators/routing/RoutingGraphIsValid.h:1:0,
                 from /home/james/research/zio/src/lanelet2/lanelet2_validation/src/validators/RoutingGraphIsValid.cpp:1:
/home/james/research/zio/src/lanelet2/lanelet2_validation/include/lanelet2_validation/BasicValidator.h:18:25: error: enclosing class of constexpr non-static member function ‘const char* lanelet::validation::MapValidator::name()’ is not a literal type
   constexpr const char* name() { return ""; }
`

**Comment by poggenhans** [comment]
Ah, ok. That is already fixed in df851e20e7535a8b5c6d19ce6946abb528a47de7 :wink:
