### ISSUE TITLE
new package use

### ISSUE THREAD

**Issue by xiaozhi12345678** [fzi-forschungszentrum-informatik/Lanelet2#20]
Hi,I write a package to join in the Lanelet2-master,and it compile successfully.After that I write a cpp to test the package, but comes the error "can't find that file or directory
 #include <lanelet2_interface/lanelet2_interface.h>", lanelet2_interface is the package that I write.All CMakeLists.txt are imitated by examples.Could you please is there something I ignored?Or how could I do?thank you!

**Comment by poggenhans** [comment]
Seems like there is some `include_directories` entry missing in your CMakeLists. But this is really not a question that is related to Lanelet2 in any way. This is purely cmake-related.

stackoverflow would be a better place for these kinds of questions.
