### ISSUE TITLE
possible bug in getHardcodedChangeType() function

### ISSUE THREAD

**Issue by mitsudome-r** [fzi-forschungszentrum-informatik/Lanelet2#201]
I have noticed that when there is a linestring with `lane_change:left=no` and `lane_change:right=yes`, the lanelet2 routing graph doesn't allow you to change lane in either way.

When I look at [the code](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/1e659dab3cade16ab8aebc62af1f44126ed525a7/lanelet2_traffic_rules/src/GenericTrafficRules.cpp#L72), it seems like it is expecting to have only `lane_change:right=yes` without setting `lane_change:left=no` if you only want the vehicle to do the right lane change(otherwise it will return no lanechange in L72), but the [document](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/1e659dab3cade16ab8aebc62af1f44126ed525a7/lanelet2_traffic_rules/src/GenericTrafficRules.cpp#L72) states that you have to set both tags if you are using these tags. Which one is true?

**Comment by poggenhans** [comment]
Yes, that looks like a bug in the code. Would you mind creating a PR to fix this (and ideally add a test that covers it)?
