### ISSUE TITLE
Creating custom traffic rules for a vehicle subtype

### ISSUE THREAD

**Issue by PPeltzer** [fzi-forschungszentrum-informatik/Lanelet2#202]
Hello,

I want to prevent a custom vehicle subtype from passing over certain lanelets. Since I want to reuse the existing `GermanTrafficRules` implementation, I'm inheriting from that. Also, as `Participants::Vehicle` and its subtypes are specially handled in this base class, I explicitly want to use a new, custom subtype to reuse the existing handling (lets say `vehicle:foo`) and I'm creating a routing graph for this subtype later on.

My custom `TrafficRules` class:
```
// header
class fooVehicle : public GermanVehicle {
 public:
    using GermanVehicle::GermanVehicle;

    Optional<bool> canPass(const RegulatoryElementConstPtrs& regElems) const override;
};

// cpp
RegisterTrafficRules<fooVehicle> fooRules(Locations::Germany, "vehicle:foo");
}  // namespace

Optional<bool> fooVehicle::canPass(const RegulatoryElementConstPtrs& regElems) const {
  // Do some stuff in here and return false for the desired regElemet
}
```

However, as it turns out, it is not possible to create a custom traffic rules set for any `vehicle` subtypes and this might well be unwanted behavior judging from the code/comment ([line 15/16 in TrafficRulesFactory.cpp](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/1e659dab3cade16ab8aebc62af1f44126ed525a7/lanelet2_traffic_rules/src/TrafficRulesFactory.cpp#L15)):
```
TrafficRulesUPtr TrafficRulesFactory::create(const std::string& location, const std::string& participant,
                                             TrafficRules::Configuration configuration) {
  auto& registry = instance().registry_;
  auto elem = registry.find(std::make_pair(location, participant));
  const std::string vehicle = Participants::Vehicle;
  if (participant.compare(0, vehicle.size(), vehicle) == 0) {
    // second try for vehicle types
    elem = registry.find(std::make_pair(location, std::string(Participants::Vehicle)));
  }
  ...
  ```
While the custom traffic rules should be located correctly by the first `find` call, the "second try" will overwrite it nonetheless (so it is actually not a second, optional run as it is suggested by the comment). I suppose that the if condition is missing an according check?
```
if (elem == registry.end() && participant.compare(0, vehicle.size(), vehicle) == 0) 
...
```
If this is not the case and it is actually the desired behavior: Is there another way which I'm missing right now to reach my goal?

Regards,

Patrick

**Edit:**
[Overriding](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_core/doc/LaneletAndAreaTagging.md#overriding) is actually the preferable way to tackle this problem and I can easily realize blocking certain lanelets. So my special problem is solved; however, I think this issue is still relevant for more complex situations which need to be handled using regulatory elements and therefore with custom traffic rules. So I keep this open :wink:

**Comment by poggenhans** [comment]
That looks a lot like a bug in the `TrafficRulesFactory`. A PR with your suggested change would be great to help us fix this.
