### ISSUE TITLE
Matching The HD Map with Point Cloud Map 

### ISSUE THREAD

**Issue by mfapakhan** [fzi-forschungszentrum-informatik/Lanelet2#220]
Hello to everyone;

I am writing from Turkey.
I want to match my point cloud map with the HD map produced according to the point cloud map.
I created a UTM projection with this code sample below and projected the HD map according to the projector.

```
lanelet::GPSPoint gps_point;
gps_point.lat = 39.72497048;
gps_point.lon = 33.36829990;
lanelet::Origin origin(gps_point);
lanelet::projection::UtmProjector projector(lanelet::Origin(gps_point), true, true);


lanelet::LaneletMapPtr map = lanelet::load(lanelet2_filename, projector, &errors); 
```

I am sure I used correct and precise origin but when opening the RViz to analyze aligning result, I saw that there was still transitional and rotational offset between HD Map and Point Cloud Map. What can be the reason of this mis-alignment?

Thanks and best regards.

**Comment by mfapakhan** [comment]
Hello again;

To summarize my all process;

1. I have a 3D Point Cloud Data and an HD map in Lanelet2 format is produced according to the 3D point cloud data.

2. I try to align them in same frame and to do this I use the map.launch.xml from tier4 repo. (git@github.com:tier4/AutowareArchitectureProposal.proj.git) ==> In this launch file, a lanelet map and a 3D Point cloud map are loaded to the ROS system, respectively.

3. After the loading process, I open the RViz to visualize the maps and see that the maps are different locations. When I analyze the reason of the being different locations, I understand that in the tier4 repo the lanelet2 map is projected according to the MGRS projection system while the point cloud map is projected according to the UTM projection system.

4. To solve the problem and remove the differences, I reorganize the code sample responsible for loading lanelet2 map to the system. In this reorganization, I remove the code doing the MGRS projection and add a code doing the UTM projection. (The adding code sample is below:
```
lanelet::GPSPoint gps_point;
gps_point.lat = 39.72497048;
gps_point.lon = 33.36829990;
lanelet::Origin origin(gps_point);
lanelet::projection::UtmProjector projector(lanelet::Origin(gps_point), true, true);


lanelet::LaneletMapPtr map = lanelet::load(lanelet2_filename, projector, &errors); 
```
This code sample expects a precise origin from me to align the lanelet2 map with 3D point cloud data. I measure and calculate the origin precisely and adding this origin to the code.

5. When running this map.launch.xml with reorganized code sample, I see that the 3D point cloud map and lanelet2 map are in the same frame but there are a little bit transitional and rotational offset. This offset is nearly 2 degrees and 3-5 meters. However, I don't understand the reason of the offset and I search about it.

I hope I described my situation clearly. If you have any question, I can give additional information.

Thanks and best regards.

**Comment by poggenhans** [comment]
And which tool handles the transformation and rendering of the pointcloud? I'm asking because the default behavior of the `UtmProjector` to offset the transformed data so that the position of the origin is equal to (0,0) in the local coordinate system is a bit unique to lanelet2. It would surprise me if other tools implemented that in the same way.

One of the reasons why we have this offset behavior by default is that the 32bit floats used by ogre/rviz are not enough to precisely represent a whole utm tile. So if rviz needs to do a few transformations in the background to transform map and pointcloud into the same frame and these transformation are in the range of a few 100km, that might also be a potential cause of your problem.

**Comment by hyeonmin11** [comment]
> Hello to everyone;
> 
> I am writing from Turkey. I want to match my point cloud map with the HD map produced according to the point cloud map. I created a UTM projection with this code sample below and projected the HD map according to the projector.
> 
> ```
> lanelet::GPSPoint gps_point;
> gps_point.lat = 39.72497048;
> gps_point.lon = 33.36829990;
> lanelet::Origin origin(gps_point);
> lanelet::projection::UtmProjector projector(lanelet::Origin(gps_point), true, true);
> 
> 
> lanelet::LaneletMapPtr map = lanelet::load(lanelet2_filename, projector, &errors); 
> ```
> 
> I am sure I used correct and precise origin but when opening the RViz to analyze aligning result, I saw that there was still transitional and rotational offset between HD Map and Point Cloud Map. What can be the reason of this mis-alignment?
> 
> Thanks and best regards.



> 

how did you use hdmap in ros?
