### ISSUE TITLE
Shorten the distance between lanelet.centerline points

### ISSUE THREAD

**Issue by zhucj991** [fzi-forschungszentrum-informatik/Lanelet2#222]
hello, i have a question.
I want to query lanelet.centerline() function, but it seems that the distance between consecutive points of  centerline(Linestring3d) is depending on Point's position of Linestring3d. 
Can I shorten the distance between centerline's point,  but not change the linestring of 
this lanelet?
![image](https://user-images.githubusercontent.com/89432684/140903134-e60b1371-7e96-4364-961e-1ab9947c2768.png)

**Comment by poggenhans** [comment]
No, not possible. The algorithm for the centerline calculates the centerline from a voronoi graph and that graph is defined by the points of the two borders. If you are not happy with that, you have to compute the centerline yourself and overwrite it in the lanelet with `setCenterline`.

**Comment by zhucj991** [comment]
thanks, thank for you explain the rule of centerline calculate.
