### ISSUE TITLE
could not find a package configuration file provided by "mrt_cmake_modules"

### ISSUE THREAD

**Issue by eternalsilencer** [fzi-forschungszentrum-informatik/Lanelet2#234]
i debug with clion ，when i load lanelet2_core cmakelists ,find this error , how i can i load mrt_cmake_modules?
![image](https://user-images.githubusercontent.com/51810383/150133357-238af8d7-78b5-44dd-a739-37b5b4119488.png)

**Comment by poggenhans** [comment]
Well, as the message states, you have to make sure that the path where `mrt_cmake_modules` is installed is in your `CMAKE_PREFIX_PATH` variable.

If you are using catkin, you should make sure that clion sets this variable in a similar way as sourcing `setup.bash` would set it.
