### ISSUE TITLE
Update ROS package

### ISSUE THREAD

**Issue by Axlef** [fzi-forschungszentrum-informatik/Lanelet2#235]
I've noticed that the ROS package in the ubuntu repo (e.g. ros-noetic-lanelet2) looks quite old since they seem based on the tag 1.1.1 which date back from Sept 14, 2020.

Since then a few bugs were fixed, and the matching module has been added. The last commit on master is six month old, and it looks quite stable. Would it be possible to release a new up to date version in the ROS package/ubuntu repo (maybe add a new tag 1.1.2 on the last commit?) ?

**Comment by tristankpka** [comment]
I also need this update as the python API has been extended lately.

**Comment by mantkiew** [comment]
I'm also hoping for a new release after https://github.com/fzi-forschungszentrum-informatik/Lanelet2/pull/245 has been merged.

**Comment by mantkiew** [comment]
@poggenhans now that the recent PRs have been merged. Could you please make a new binary ROS package release?
Or are you still planning some more changes before that?

**Comment by mantkiew** [comment]
@poggenhans Congrats on the 1.2 release! When can we expect for the binary package to be updated? I'm still getting
```
ros-noetic-lanelet2 is already the newest version (1.1.1-1focal.20210726.193049).
```

**Comment by poggenhans** [comment]
Sorry it took so long. We are also planning a release for ros2, that should follow soon.

The packages are currently only available on ros staging apt repository. Every few weeks the ros maintainers make a coordinated sync of all new packages to the official apt repo announce it on [ros discourse](https://discourse.ros.org/c/release/noetic/66).

**Comment by immel-f** [comment]
There have been new ROS releases for ROS2 now as well with 1.2.1, so I am closing this issue
