### ISSUE TITLE
[Question] Finding intersecting point between Lanelets

### ISSUE THREAD

**Issue by rodrigoqueiroz** [fzi-forschungszentrum-informatik/Lanelet2#236]
I have some questions regarding how Lanelet handles intersections and the geometry API.

When there is a conflict between Lanelets (as an intersection), we can retrieve the conflicting ones along the route using

route.conflictingInMap(lanelet)

This brings a list of other lanelets, but no other information on how they intersect. Is it possible to find the point (a 2D or 3D Point) where each intersection occurs, and the point (or order) along the lanelet longitudinal distance ?

For example, assuming the route is lanelet A, while lanelets B and C intersect:

<img width="278" alt="Screen Shot 2022-01-20 at 3 28 34 PM" src="https://user-images.githubusercontent.com/5768004/150417078-7170bd1f-1184-4a9e-aa4e-a9193834bf9f.png">

The conflictingInMap will retrieve lanelets B and C. My goal is to find:
- The exact point in the cartesian space where they occur 
- The point along the Lanelet distance. This is important to understand how C happens before B, although B is closer to the beginning of the Lanelet A if we measure the distance between two points in  the cartesian system with the geometry API.

**Comment by poggenhans** [comment]
You are probably looking for the [intersection](https://www.boost.org/doc/libs/1_78_0/libs/geometry/doc/html/geometry/reference/algorithms/intersection/intersection_3.html) algorithm provided by boost geometry. If you can assume that the lanelet always fully crosses (not only touches) the lanelet, you could use it with the centerlines:
```c++
BasicPoints2d intersections;
boost:geometry::intersection(laneletA.centerline2d().basicLineString(), laneletB.centerline2d().basicLineString(), intersections);
```
and then use [toArcCoordinates](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/21e911efcde20fc281e731b5abb0167e9f00e0c2/lanelet2_core/include/lanelet2_core/geometry/LineString.h#L122) to find which of these intersections occurs at which travel distance along the centerline of lanelet A.

If you have to assume that the lanelets can also touch each other without the centerlines touching, you can compute the intersection with the 2D polygons of the two lanelets (the result would have to be a `BasicPolygonsWithHoles`) and then project the points of the outer polygon onto your lanelet to find out which one is the closest.
