### ISSUE TITLE
RoutingGraphContainer in Python

### ISSUE THREAD

**Issue by jannik-hi** [fzi-forschungszentrum-informatik/Lanelet2#238]
Hi, is there any possibility to use the RoutingGraphContainer in Python? As far as I can see, it is not included in the boosted code. I want to search for conflicting lanelets from different participants (e.g. bicycle_lane and road at an intersection). Alternatively, is there another elegant way to get this solved in Python?

**Comment by poggenhans** [comment]
As of now, there is no equivalent of this in python. But you could use [intersects3d](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/21e911efcde20fc281e731b5abb0167e9f00e0c2/lanelet2_python/python_api/geometry.cpp#L360) on each pair of lanelets from the two routing graphs to find out if they intersect, which is essentially the same thing the RoutingGraphContainer does internally.

If you want to be more efficient, you can search the lanelet submap of the one routing graph with the bounding box of each lanelet of the other routing graph to obtain potentially conflicting lanelet candidates on which you have to run `intersects3d`.
