### ISSUE TITLE
Location changes do not work when write osm map

### ISSUE THREAD

**Issue by blacksheep0303** [fzi-forschungszentrum-informatik/Lanelet2#239]
Thanks for your help first.
I want to change the position of points in the map.My code is as following:

> LaneletMap lanelet_map;
> lanelet_map.add(temp_lanelet);

and use 
> lanelet_map.pointLayer.find(point_id)->x() = temp_x;  
to change point's location with specific ID.

However, when I writed map I found that the position of the point had not changed.
I used the   lanelet::write("lanelet2_try.osm", lanelet_map);   function.

I want to know how to change the position of the points in the map.
Thanks again for your help!

**Comment by poggenhans** [comment]
Hm, what you describe should work and has been done many times. I'm afraid without a minimal example to reproduce your problem, we won't be able to help you there.

**Comment by blacksheep0303** [comment]
@poggenhans Thank you for your reply. I found that this problem was caused by my negligence. Now I've solved it. Thanks again for your help!
