### ISSUE TITLE
 "possiblePaths.size" return 0  while merging two Lanelets

### ISSUE THREAD

**Issue by ugurcaliskann** [fzi-forschungszentrum-informatik/Lanelet2#240]
Hi all,

I merged two Lanelets which are using lanelet::Lanelets, and I created LaneletMap. When I use LaneletMap for generating RoutingGraph  " pedestrian_rules_ptr_=lanelet::traffic_rules::TrafficRulesFactory::create(lanelet::Locations::Germany,lanelet::Participants::Pedestrian);
  ped_routing_graph_ptr_ = lanelet::routing::RoutingGraph::build(*lanelet_map_ptr_, *pedestrian_rules_ptr_); " like this .
  "possiblePaths.size" return 0  , where am i doing wrong?

**Comment by poggenhans** [comment]
Sorry, no idea without at least an image of your map. Might be that:
- The lanets don't share points
- They are not tagged as bidirectional lanelets
- Or not correctly tagged as pedestrian lanelets
- They are not correctly geometrically aligned
- ...
