### ISSUE TITLE
Projector cannot be instantiated from Python

### ISSUE THREAD

**Issue by KleinYuan** [fzi-forschungszentrum-informatik/Lanelet2#242]
It seems the Projector cannot be instantiated from Python. To reproduce it:

```
>>> import lanelet2
>>> lanelet2.projection.Projector(lanelet2.io.Origin(0,0,0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: This class cannot be instantiated from Python
```

Is it because this class is not bind? I have no issue with UTMProjector tho.
It looks like already bind-ed: https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/cc815028e9faf913824b2a4aff5d111d153213ba/lanelet2_python/python_api/projection.cpp#L16-L17

**Comment by m-naumann** [comment]
The `Projector` class is just defining the interface, using the `UtmProjector` is most probably what you want. Or why are you intending to instantiate the base class?

**Comment by KleinYuan** [comment]
> The `Projector` class is just defining the interface, using the `UtmProjector` is most probably what you want. Or why are you intending to instantiate the base class?

The reason why is that we are trying to do a custom forward/reverse. Namely, we need to write a new class either inheriting the projector or wrap on top of it. Neither seems working. If I do a new class inheriting Projector, the error is as follows:

```
Boost.Python.ArgumentError: Python argument types in
    lanelet2.io.load(str, Projector)
did not match C++ signature:
    load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > filename, lanelet::Origin origin)
    load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > filename, lanelet::Projector projector=<lanelet2.projection.MercatorProjector object at 0x7f82a22efad0>)
```

**Comment by m-naumann** [comment]
Okay, makes sense. 

Supporting classes inherited in python is some more effort: https://www.boost.org/doc/libs/1_78_0/libs/python/doc/html/reference/high_level_components/boost_python_wrapper_hpp.html#high_level_components.boost_python_wrapper_hpp.introduction

So either you'd have to add that, or implement your custom projection in cpp.

**Comment by KleinYuan** [comment]
> Okay, makes sense.
> 
> Supporting classes inherited in python is some more effort: https://www.boost.org/doc/libs/1_78_0/libs/python/doc/html/reference/high_level_components/boost_python_wrapper_hpp.html#high_level_components.boost_python_wrapper_hpp.introduction
> 
> So either you'd have to add that, or implement your custom projection in cpp.

Right. I think maybe we can add a default projector under [the projector](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/tree/master/lanelet2_projection/src) for the purpose (, and bind it to python).

**Comment by m-naumann** [comment]
Makes sense, see also #244 for an example, maybe you can even contribute your projector

**Comment by KleinYuan** [comment]
I ended up with following the PR your recommended and have my problem solved! Thanks for the great suggestions @m-naumann
