### ISSUE TITLE
Centerline Output

### ISSUE THREAD

**Issue by j4142** [fzi-forschungszentrum-informatik/Lanelet2#243]
Hey,

I am trying to compute the centerline for the lanelets after loading an osm file using _lanelet2.io.load_. While I am able to fetch the leftBound and rightBound of the lanelets, the output of centerline is like _[id: 0 point ids: 0, 0, 0, 0]_.

I wanted to know what the issue maybe here and how to fix it as I need the centerlines for my purpose. Is it that the centerline coordinates are in-fact getting computed but not stored? If so, how can those coordinates be viewed?

Thanks!

----------------------------------------------------------
Code block is as follows:

```
import lanelet2

map = lanelet2.io.load("path_to_the_osm_file", lanelet2.io.Origin(0,0))

for elem in map.laneletLayer:
    print(elem.id, elem.centerline)

```

**Comment by ceyhunblr** [comment]
How can you solve it?
