### ISSUE TITLE
How to know which functions are available in Lanelet2 Python and how to use them, and question about Attributes

### ISSUE THREAD

**Issue by 150205** [fzi-forschungszentrum-informatik/Lanelet2#247]
I have some difficulty using lanelet2's functions. How can I get which of all the functions Python can call? And how to use these functions? Is there any API documentation for Lanelet2 Python?

And how do I get the value of attributes? My code is as follows：
`for lanelet in map.laneletLayer:
for attributes in lanelet.attributes:
atr=attributes
`
For example I can get `(location,urban)`What data type is this？And how can I get a numpy array or list or dictionary like `['location','urban']`

**Comment by poggenhans** [comment]
There is no good documentation on the python implementation. The best source of truth is either the [source code](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_python/python_api/core.cpp#L550) itself, or just what python tools themselves can tell you from inspecting the code. And there is the small [python example](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_examples/scripts/tutorial.py) that shows the basics.

Regarding your question: attributes behave similarly to dicts, so `lanelet.attributes["location"] == "urban"`.
