### ISSUE TITLE
Possible issue in LaneletMapPtr Route::getDebugLaneletMap()

### ISSUE THREAD

**Issue by dogplate** [fzi-forschungszentrum-informatik/Lanelet2#249]
I've been trying to write .osm file of laneletMap that comes from getDebugLaneletMap(). 
Here is my code as follows.
`ConstLanelet lanelet = map_->laneletLayer.get(startLanelet[0].second.id());`
`ConstLanelet toLanelet = map_->laneletLayer.get(goalLanelet[0].second.id());`
`Optional <routing::Route> optRoute = routingGraph_->getRoute(lanelet, toLanelet, 0);`
`write("/debug_path.osm", *(optRoute->getDebugLaneletMap()),Origin(origin_));`

Actually, I did the same thing in 0.8.0 version of lanelet2 and it worked fine with it.
But In the latest version of lanelet2, the output of osm file keep crash with no 'way' component in it.

I think it's because LaneletMap() is deprecated and replaced by LaneletSubmap().
So is there any solution to write debugLaneletMap?

**Comment by poggenhans** [comment]
Sorry, with this little information it's hard to find the cause of your issue. `getDebugLaneletMap` is working fine. Are you sure the route object returned by getRoute is valid?

That `LaneletMap` is deprecated is probably a misunderstanding. Not the whole `LaneletMap` is deprecated, just the method `laneletMap` as part of the `Route` is deprecated. But this is not related to your problem.
