### ISSUE TITLE
How can I tell if the lanelet is inside the intersection or on the road?

### ISSUE THREAD

**Issue by LilyLove0810** [fzi-forschungszentrum-informatik/Lanelet2#250]
I I didn't find a tag that effectively distinguishes intersections and road segments

**Comment by poggenhans** [comment]
There is no officially defined tag for marking parts of intersections. You can add one yourself, if you need it. Or draw a polygon around the intersection and tag that.

Lanelet2 has no clear distinction between "road segments" and "intersections" as other map formats. Whereever two traffic participants may collide is a potential intersection. So intersections are rather defined in terms of a geometrical intersection of lanelets than by an external tag.
