### ISSUE TITLE
Lanelet2 for Waterways

### ISSUE THREAD

**Issue by ecschuetz** [fzi-forschungszentrum-informatik/Lanelet2#251]
I would like to create a Lanelet2 map consisting of waterways and regulatory navigation signs. Basically an extension of lanelet2_maps.
Are there any approaches to this that I haven't found yet?
Is it enough to modify `lanelets.mapcss`, `lines.mapcss` and `laneletpresets.xml` and insert the new traffic sign images?

**Comment by immel-f** [comment]
I am not aware of any existing approaches in this direction, but the files you mentioned are just related to the visualization of elements in JOSM. If you only want to change the visualization, changing these should be enough.
