### ISSUE TITLE
Odd centerline computation of the lanelet

### ISSUE THREAD

**Issue by francocipollone** [fzi-forschungszentrum-informatik/Lanelet2#260]
Hey there! I ran into this weird behavior when computing the centerline.

### Summary

When no centerline is passed to the lanelet, it is calculated automatically out of the left and right linestrings.
I found a case in which the algorithm returns a weird centerline.

### System
 - Ubuntu 20.04
 - Binaries installed via: `apt install ros-foxy-lanelet2`
 
### Context

 - I am using an osm file which is 2-lane road with an increasing elevation which tries to replicates a parking garage ramp, like:
      <img src="https://user-images.githubusercontent.com/53065142/196976784-664baa50-459e-482e-8b40-a5a591fe4840.png" 
  width=200>

 - Here there is the osm file: [lanelet2_parking_garage_ramp.zip](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/files/9831065/lanelet2_parking_garage_ramp.zip)
 - In JOSM (Projection in the 2d plane): 
      <img src="https://user-images.githubusercontent.com/53065142/196977418-9880b965-0845-4e7d-9bb8-8c4ff85f96f8.png" 
  width=400>

### Actual Behavior

The centerline that is computed for any of those two lanes in the map aren't valid centerlines:

![image](https://user-images.githubusercontent.com/53065142/196977855-afea7ed1-2a6e-4b2c-835a-f778d6c81767.png)

The red line is the computed centerline for the left and right linestrings of the lanelet with id(1374) (in gray)

<details>
<summary>Click here to see the script for 3d-plotting the lanelet</summary>

```py
#!/usr/bin/env python
import lanelet2
import matplotlib.pyplot as plt

from lanelet2.projection import UtmProjector

def PlotLanelet(lanelet):
    points = {"center_x": [], "center_y": [], "center_z": [],
              "left_x": [], "left_y": [], "left_z": [],
              "right_x": [], "right_y": [], "right_z": []
              }
    for node in lanelet.leftBound:
        points["left_x"].append(node.x)
        points["left_y"].append(node.y)
        points["left_z"].append(node.z)
    for node in lanelet.rightBound:
        points["right_x"].append(node.x)
        points["right_y"].append(node.y)
        points["right_z"].append(node.z)
    for node in lanelet.centerline:
        points["center_x"].append(node.x)
        points["center_y"].append(node.y)
        points["center_z"].append(node.z)

    axes = plt.axes(projection='3d')
    axes.plot3D(points["left_x"], points["left_y"], points["left_z"], 'grey')
    axes.plot3D(points["right_x"], points["right_y"],
                points["right_z"], 'grey')
    axes.plot3D(points["center_x"], points["center_y"],
                points["center_z"], 'red')
    plt.show()


def Main():

    example_file = "lanelet2_parking_garage_ramp.osm"
    projector = UtmProjector(lanelet2.io.Origin(0, 0))
    map = lanelet2.io.load(example_file, projector)
    PlotLanelet(map.laneletLayer[1374])

if __name__ == "__main__":
    Main()

```

</details>

The centerline calculated isn't a valid one. It might be related to the algorithm for computing the centerline using some xy projections in order to do so. And given this particular shape, it reaches a limit on which geometry for the lanelet supports

### Expected behavior

To obtain a centerline that is "valid"

**Comment by immel-f** [comment]
This is indeed an issue with the centerline calculation, as it both uses xy projection for the calculation and also has problems with circular lanelets for the centerline. You could probably make your use case work by splitting your large lanelet into multiple smaller segments.
