### ISSUE TITLE
Could not find ele attribute

### ISSUE THREAD

**Issue by 1475015695** [fzi-forschungszentrum-informatik/Lanelet2#261]
Hi, Thank you for your great contribution. I can't read the point's ele attribute (the ele is stored in the OSM file). Thanks for any help.

OSM example：
![Screenshot from 2022-11-29 20-56-35](https://user-images.githubusercontent.com/34376638/204534958-85511ae6-ae0a-4c13-b319-62fc0667b0cc.png)

code example：
        cout<<p.id()<<","<<p.attribute("local_x").value()<<","<<p.hasAttribute("mgrs_code")<<","<<p.hasAttribute("ele")<<endl;

output：
        55,-261.2215,1,0

**Comment by poggenhans** [comment]
The ele tag will simply become the `z` coordinate of the point, that's why it no longer appears in the attributes.

**Comment by 1475015695** [comment]
> The ele tag will simply become the `z` coordinate of the point, that's why it no longer appears in the attributes.

Yes. But the 'z' coordinate is calculated by longitude and latitude, here ele and local_ x,local_ y is consistent(Local coordinate). How can I get this value. Thank you for your reply

**Comment by 1475015695** [comment]
> After the model is loaded using a given projector, the lat/lon/ele change into x/y/z coordinates.
> 
> I guess your problem is that you would like to have both the `ele` and the `z` at the same time? You can calculate elevation back by using the projector, that will transform x/y/z back to lat/lon/ele.

Thank you. It works.
