### ISSUE TITLE
How to convert osm data into net.xml data?

### ISSUE THREAD

**Issue by ShenZC25** [fzi-forschungszentrum-informatik/Lanelet2#262]
I tried to use SUMO to convert osm files from INTERACTION dataset, but encountered an error:

Error: No nodes loaded.
Quitting (on error).

I also tried to convert other osm files from [www.openstreetmap.org], and it worked. I guess the problem is that Lanelet2 uses a different way to represent roads compared with other osm generators.
So it's there a method I can use to convert osm data from INTERACTION dataset into net.xml data? Your help will be very much appreciated.

**Comment by poggenhans** [comment]
Correct, in lanelet2 the data within an osm file has a completely different meaning than in "classical" OSM. In lanelet2, ways in an .osm file are just the border of a lane, not whole roads as in OSM. I'm not aware of an existing converter from lanelet2 to sumo.
