### ISSUE TITLE
Exporting map to osm; Lanes not aligned with roads

### ISSUE THREAD

**Issue by javierpastorfernandez** [fzi-forschungszentrum-informatik/Lanelet2#265]
Hi,
I created a Map with Lanes and locations expressed in UTM.
Once the map is created, I use the following function to export it :

`projector = UtmProjector(lanelet2.io.Origin(0,5.25))`
 `lanelet2.io.write(path, map, projector)`

Whenever I open the .osm file, the lat, and lon values obtained from the projection do not match the underlying geography (roads), nor the values calculated using python libraries such as PyProj, or webpages:
https://franzpc.com/apps/conversor-coordenadas-geograficas-utm.html

I have tried with many combinations for the Origin -> [0,9], [0,6],  [48.77,5.242], but I still get this misalignment.

My data is in UTM Zone 32.

Thank you in advance!

**Comment by immel-f** [comment]
The UTM system requires the origin used in the projector to be as close as possible to the map data to perform the projection to WGS84 correctly (see the lanelet2_projection [readme](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_projection/README.md). You need an origin in lat/lon very close your mapping area (best just one of your mapped points), your example origins are not in the same UTM zone.
