### ISSUE TITLE
Lanelet2 vs. OpenDrive 2.0 Area Concept

### ISSUE THREAD

**Issue by mantkiew** [fzi-forschungszentrum-informatik/Lanelet2#266]
Hello, currently OpenDrive 1.x and Lanelet2 are largely incompatible. However, there's a new initiative within OpenDrive called "Area Concept" to align it with common GIS methods. It seems to me that the Area Concept basically moves towards Lanelet2 design without explicitly mentioning it.

https://www.asam.net/index.php?eID=dumpFile&t=f&f=3907&token=fffa694711f0cd3cc37e61f38587b3a308e9a720#_concept_paper_wp05_area_model

It would be great to have a detailed comparison between Lanelet2 design and OpenDrive Area Concept design (which can replace the OpenDrive 1.x modeling using reference line).

**Comment by m-naumann** [comment]
Thanks for this insight. From the first glance at the [comparison](https://www.asam.net/index.php?eID=dumpFile&t=f&f=3907&token=fffa694711f0cd3cc37e61f38587b3a308e9a720#tab-differences_area_concept_opendrive), the Area Layer looks much like lanelet2. The largest difference I spot is that we model the "traffic area" as union of all lanelets and other polygons, and the lane markings as part of them, whereas in the Area Concept, there are [different layers](https://www.asam.net/index.php?eID=dumpFile&t=f&f=3907&token=fffa694711f0cd3cc37e61f38587b3a308e9a720#img-layer_structure) for each of these. Still, this concept would make conversion much easier, I guess.
