### ISSUE TITLE
Questions about how to transform the lanelet-osm into normal osm 

### ISSUE THREAD

**Issue by ShenZC25** [fzi-forschungszentrum-informatik/Lanelet2#269]
Hello, I'm using an osm map in lenalet2 format, but I need an ordinary osm map now. How can I export it to an ordinary osm map?
Thank you very much.

**Comment by immel-f** [comment]
The lanelet2 format, while using the .osm file format, does not conform to the osm standard, since regular osm maps are "SD" navigation maps only. A conversion is not possible as the internal structure of lanelet2 maps and osm navigation maps are completely different.
