### ISSUE TITLE
Does Lanelet support polygon lanes

### ISSUE THREAD

**Issue by sree9578** [fzi-forschungszentrum-informatik/Lanelet2#272]
I have Polygon lanes 
Does lanelet automatically create a left and right lanes
How can i establish connectivity and convert them as lanelet ?

**Comment by immel-f** [comment]
Sorry for the late response, but lanelets require a left and right boundary. You would need to calculate these boundary line strings yourself from the polygons and also infer the connectivity of the polygon lanes.
