### ISSUE TITLE
hdmap in ros

### ISSUE THREAD

**Issue by hyeonmin11** [fzi-forschungszentrum-informatik/Lanelet2#276]
Does Lanelet2 made to use osm map like hdmap in ros?
Are there any way to use hdmap in ros? if it does, please explain me. thanks

**Comment by hyeonmin11** [comment]
I want to know how to use lanelet2 in hdmap format

**Comment by immel-f** [comment]
Lanelet2 is a separate HD map format which uses the .osm file format but does not conform to the OSM standards. If you want to convert lanelet2 maps into a different HD map format you would need to look for existing converters or implement one of your own
