### ISSUE TITLE
Provide PyPI package for multiple python versions using cibuildwheel

### ISSUE THREAD

**Issue by johschmitz** [fzi-forschungszentrum-informatik/Lanelet2#287]
Great that you started offering a [package](https://pypi.org/project/lanelet2/) on PyPI.
Would it be possible though to build for multiple Python versions using [cibuildwheel](https://github.com/pypa/cibuildwheel)?
I am interested to use this together with Blender but Blender comes with its own Python distribution currently based on 3.10.x

Here is an example how I implemented this for another package, it worked just fine basically just following the standard example:
https://github.com/phillipd94/pyclothoids/blob/master/.github/workflows/build_wheels.yaml

**Comment by poggenhans** [comment]
Sadly, cibuildwheel doesn't work for us. Lanelet2 uses boost::python for the python bindings, so we would need a boost python that is build for all the python versions that we want to release. Or build it ourselves. Some of our thirdparty dependencies are also not available, so we would have to build them too. So we essentially recreated the cibuildwheel approach manually.

If you are interested in 3.10, feel free to file a PR :wink:. The existing job can probably easily be extended to a matrix job.

**Comment by johschmitz** [comment]
Alright, I see. If I find time to get to this before you guys do it I will submit a PR.
