### ISSUE TITLE
[Question] Handling Bi-directional Lanelets

### ISSUE THREAD

**Issue by ahmeddesokyebrahim** [fzi-forschungszentrum-informatik/Lanelet2#288]
Hi there, 

I am trying to use Lanelet2 with bi-directional lanes and I have some questions. 

## `one_way` tag
I have found the information in Lanelet2 repository that is speaking about the [direction](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_core/doc/LaneletAndAreaTagging.md#direction) using the `one_way` tag. 

When I set the tag to be `no` to a lanelet in my map that I want it to be bi-directional, it is not making any difference in reading the lanelets properties, for example left and right boundaries. 
So, if you depend on calculating the lanelet angle by some utility function, it will still provide the angle in normal driving direction. 

My first questions :  what is the impact of this tag ? and how does it change the lane properties ?

## `LaneletType` enum
I can find that there is LaneletType
https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/fe47c8feccf60879d394bd562d472056ecb7adc1/lanelet2_core/include/lanelet2_core/primitives/Lanelet.h#L16
But I did find this enum is used in Lanelet2 source code.

My second question : how Lanelet2 is using this emum and how can I get benefits out of it ?

## Inverting
I have tried to invert the intended lane of bi-directional driving by using the e Lanelet class `invert()` method
https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/fe47c8feccf60879d394bd562d472056ecb7adc1/lanelet2_core/include/lanelet2_core/primitives/Lanelet.h#L232

However, that introduced some challenges in my project where other components were reading the same lanelet with its original map properties (not-inverted). 

My third questions : what is the recommended way in Lanelet2 to read such inverted lanelet across multiple SW components ?

Thanks a lot and looking forward to your answers :)

**Comment by poggenhans** [comment]
## one_way tag
This tag affects how a lanelet is treated when creating a *routing graph*. If its false (or not set), only its non-inverted version will become a part of the graph. It its true both its non-inverted and its inverted version will be a node in the graph.

One of the core concepts of lanelet2 is separating the geometrical layout of a map (in form of lanelets, linstrings, etc) from their *interpretation*. If you want to interpret the map in terms of driving direction and connectivity, you need to create a routing graph from the view of a certain traffic participant.

## LaneletType enum
Interesting, I didn't know this still existed. This enum has no use within lanelet2 any more. We probably just forgot to remove it.

## Inverting
I'm not sure what you are trying to achieve. If you invert() a lanelet, you get an inverted copy of it. This won't alter the map. If you want to alter the map, you have to modify the map itself.

**Comment by ahmeddesokyebrahim** [comment]
Thanks for the sufficient answer for my questions. I think we can close this discussion and if any further questions come around I can open a new one.
Thanks again.
