### ISSUE TITLE
[Question] Copy Lanelet Object

### ISSUE THREAD

**Issue by ahmeddesokyebrahim** [fzi-forschungszentrum-informatik/Lanelet2#298]
Hi ,

Please accept my apologizes if the answer of my questions are obvious or they are somewhere around and I did not get them.

I am asking about the proper approach for copying a [Lanelet](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/fe47c8feccf60879d394bd562d472056ecb7adc1/lanelet2_core/include/lanelet2_core/primitives/Lanelet.h#L221) class object. 
Are copy constructor and copy assignment operators implemented ? 

Another question which belongs to the same topic and context regarding the [invert](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/fe47c8feccf60879d394bd562d472056ecb7adc1/lanelet2_core/include/lanelet2_core/primitives/Lanelet.h#L232) method. Is the return a copy of the original lanelet ? or is it pointing to the original data but just inverted ?

Thanks

**Comment by poggenhans** [comment]
Your question is probably answered by the documentation on the [Primitive class](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/fe47c8feccf60879d394bd562d472056ecb7adc1/lanelet2_core/include/lanelet2_core/primitives/Primitive.h#L193) that is the base class of all lanelet primitives.

In essence: Yes you can copy them, but all copies will be shallow copies that still share the same data. The same applies to inverted primitives.

**Comment by ahmeddesokyebrahim** [comment]
Thanks for the reply.
Actually this was my understanding based on the behavior I see, but wanted to get that confirmation.

> Then it comes the interesting moment, what if I need to make a deep copy of a Lanelet object ?


Let me share some of the background of my question, as it may help.

In some cases in my project, after reading the map file and before publishing it to downstream pipeline, I need to add a new inverted lanelet (with a new ID) based on specific conditions/attributes of the map file lanelets (basically for now the `one_way` tag is no).

What I observed till now after copy that original lanelet to a new lanelet object, setting a new unique ID, and inverting it... 
-  The impact is happening on the original lanelet. I observed that because I am no longer able to drive in the original lanelet, but able to drive in the opposite direction. And I use the `LaneletMap` class `add` method for that.
https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/fe47c8feccf60879d394bd562d472056ecb7adc1/lanelet2_core/include/lanelet2_core/LaneletMap.h#L388

- The size of the map is less by one after the add operation, which is an observation I am not able to understand till now.

I do believe that the proper solution to my problem that I can have a deep copy of that lanelet object, then I can set add it afterwords without problems (knowing that `memcpy` did not compile).


Thanks again for the support and waiting for your reply

**Comment by poggenhans** [comment]
The thing about deep copies is that its hard to answer from the library side *how deep* it should be. Just the lanelet? Its linestrings too? And the points? And the regulatory elements? And their members too? And the regulatory element of their members also? You might end up copying the whole map like this.

I still didn't get what you are trying to achieve, but from what I understood you probably just want to have a new lanelet in the map that just happens to be the inverse of a lanelet that already exists. In this case, just create a new lanelet with the old lanelet's boundaries: 

```c++
Lanelet invLanelet = originalLanelet.invert();
Lanelet newLanelet = Lanelet(utils::getId(), invLanelet.leftBound(), invLanelet.rightBound());
laneletMap.add(newLanelet);
```

The way you did it doesn't work because a lanelet map expects the IDs of its elements to be unique. If you add something with an ID that already exists (even if its just the same primitive, but inverted), you break this contract.

**Comment by ahmeddesokyebrahim** [comment]
Thanks for your amazing support.
Your answer and specially the code snippet was the true opener for getting what I need.
I am closing this question now and if further inquiries happen, I will open a new one.
Much appreciated :)
