### ISSUE TITLE
__init__() of Lanelet2.core.ReguratoryElement not supported in Python

### ISSUE THREAD

**Issue by kminoda** [fzi-forschungszentrum-informatik/Lanelet2#307]
Hi,

I would like to use this library with python, and facing an issue when creating RegulatoryElement, since it does not support ctor (__init__). 

https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/a184258a3ef020648a375c5c6bac083673ecdb74/lanelet2_python/python_api/core.cpp#L1156-L1174

- Are there any reason why it's not supported? Apparently it is also the case for some other classes too, but is it due to the same reason? 
- Does anyone know how to create RegulatoryElement in Python, other than using ctor of the class?
- Are there any plans to implement the ctor? (Maybe I can also help out implementing it)

Thank you in advance!

**Comment by poggenhans** [comment]
Well as the docstring states: `This is a abstract base class that is implemented e.g. by the TrafficLight class.` If you want to use a `RegulatoryElement`, use one of it's child classes.
