### ISSUE TITLE
After last updates nodes in JOSM become invisible.

### ISSUE THREAD

**Issue by dan-dan97** [fzi-forschungszentrum-informatik/Lanelet2#31]
The problem is in lines.mapcss. When I disable this Map Paint Style the nodes become visualized but of course not in lanelet style.

**Comment by poggenhans** [comment]
Ah, yes. That got commited accidentally. You would have to remove [this](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_maps/josm/lines.mapcss#L7) entry from your sylesheet.

I'll fix in a week when I have access to our internal Git server.
