### ISSUE TITLE
Map of Karlsruhe

### ISSUE THREAD

**Issue by LongfeiDE** [fzi-forschungszentrum-informatik/Lanelet2#310]
Dear Authors of Lanelet2, 

i'm interested in your work and would like to know where i could find an example to start with. 

In the paper you mentioned that maps for large parts of Karlsruhe will be published. Could you provide link to the resources?

Thanks a lot in advance.

**Comment by poggenhans** [comment]
Lanelet2 comes with an example map: [lanelet2_maps/res/mapping_example.osm](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_maps/res/mapping_example.osm) 
The maps mentioned of the paper were published as part of the "Testfeld Autonomes Fahren" (https://taf-bw.de) and are available free of charge here: https://github.com/fzi-forschungszentrum-informatik/test-area-autonomous-driving-dataset

**Comment by LongfeiDE** [comment]
Thanks for your reply!
