### ISSUE TITLE
lanelet2_core build fails

### ISSUE THREAD

**Issue by sheraz-rasib** [fzi-forschungszentrum-informatik/Lanelet2#314]
Hello,
I am trying to build the newest lanelet2 from git. I installed ROS Melodic from ros-melodic-ros-base in my Ubuntu 18.04 and then followed your installation instructions (including the extra dependencies). I also downloaded the catkin package into the workspace. When I try to build the workspace it fails with the following error:

Profile:                     default
Extending:          [cached] /opt/ros/melodic
Workspace:                   /home/sheraz/catkin_ws
--------------------------------------------------------------
Build Space:        [exists] /home/sheraz/catkin_ws/build
Devel Space:        [exists] /home/sheraz/catkin_ws/devel
Install Space:      [unused] /home/sheraz/catkin_ws/install
Log Space:          [exists] /home/sheraz/catkin_ws/logs
Source Space:       [exists] /home/sheraz/catkin_ws/src
DESTDIR:            [unused] None
--------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
--------------------------------------------------------------
Additional CMake Args:       -DCMAKE_BUILD_TYPE=RelWithDebInfo
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
--------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
--------------------------------------------------------------
Workspace configuration appears valid.
--------------------------------------------------------------
[build] Found '11' packages in 0.0 seconds.                                    
[build] Package table is up to date.                                           
Starting  >>> lanelet2_core                                                    
_______________________________________________________________________________
Errors     << lanelet2_core:make /home/sheraz/catkin_ws/logs/lanelet2_core/build.make.006.log
In file included from /usr/include/boost/geometry/algorithms/detail/relate/de9im.hpp:24:0,
                 from /usr/include/boost/geometry/algorithms/detail/relate/interface.hpp:28,
                 from /usr/include/boost/geometry/algorithms/detail/disjoint/interface.hpp:30,
                 from /usr/include/boost/geometry/algorithms/disjoint.hpp:24,
                 from /home/sheraz/catkin_ws/src/lanelet2/lanelet2_core/src/LineStringGeometry.cpp:9:
/usr/include/boost/geometry/algorithms/detail/relate/result.hpp: In constructor ‘boost::geometry::detail::relate::matrix<Height, Width>::matrix()’:
/usr/include/boost/geometry/algorithms/detail/relate/result.hpp:69:11: error: ‘::memset’ has not been declared
         ::memset(m_array, 'F', static_size);
           ^~~~~~
/usr/include/boost/geometry/algorithms/detail/relate/result.hpp:69:11: note: suggested alternative: ‘wmemset’
         ::memset(m_array, 'F', static_size);
           ^~~~~~
           wmemset
/usr/include/boost/geometry/algorithms/detail/relate/result.hpp: In constructor ‘boost::geometry::detail::relate::mask<Height, Width>::mask(const char*)’:
/usr/include/boost/geometry/algorithms/detail/relate/result.hpp:234:15: error: ‘::memset’ has not been declared
             ::memset(it, '*', last - it);
               ^~~~~~
/usr/include/boost/geometry/algorithms/detail/relate/result.hpp:234:15: note: suggested alternative: ‘wmemset’
             ::memset(it, '*', last - it);
               ^~~~~~
               wmemset
/usr/include/boost/geometry/algorithms/detail/relate/result.hpp: In constructor ‘boost::geometry::detail::relate::mask<Height, Width>::mask(const char*, std::size_t)’:
/usr/include/boost/geometry/algorithms/detail/relate/result.hpp:247:15: error: ‘::memcpy’ has not been declared
             ::memcpy(m_array, s, count);
               ^~~~~~
/usr/include/boost/geometry/algorithms/detail/relate/result.hpp:247:15: note: suggested alternative: ‘wmemcpy’
             ::memcpy(m_array, s, count);
               ^~~~~~
               wmemcpy
/usr/include/boost/geometry/algorithms/detail/relate/result.hpp:251:15: error: ‘::memset’ has not been declared
             ::memset(m_array + count, '*', static_size - count);
               ^~~~~~
/usr/include/boost/geometry/algorithms/detail/relate/result.hpp:251:15: note: suggested alternative: ‘wmemset’
             ::memset(m_array + count, '*', static_size - count);
               ^~~~~~
               wmemset
make[2]: *** [CMakeFiles/lanelet2_core.dir/src/LineStringGeometry.cpp.o] Error 1
make[1]: *** [CMakeFiles/lanelet2_core.dir/all] Error 2
make: *** [all] Error 2
cd /home/sheraz/catkin_ws/build/lanelet2_core; catkin build --get-env lanelet2_core | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...............................................................................
Failed     << lanelet2_core:make                    [ Exited with code 2 ]     
Failed    <<< lanelet2_core                         [ 4.7 seconds ]            
Abandoned <<< lanelet2                              [ Unrelated job failed ]   
Abandoned <<< lanelet2_io                           [ Unrelated job failed ]   
Abandoned <<< lanelet2_maps                         [ Unrelated job failed ]   
Abandoned <<< lanelet2_projection                   [ Unrelated job failed ]   
Abandoned <<< lanelet2_traffic_rules                [ Unrelated job failed ]   
Abandoned <<< lanelet2_matching                     [ Unrelated job failed ]   
Abandoned <<< lanelet2_routing                      [ Unrelated job failed ]   
Abandoned <<< lanelet2_python                       [ Unrelated job failed ]   
Abandoned <<< lanelet2_examples                     [ Unrelated job failed ]   
Abandoned <<< lanelet2_validation                   [ Unrelated job failed ]   
[build] Summary: 0 of 11 packages succeeded.                                   
[build]   Ignored:   None.                                                     
[build]   Warnings:  None.                                                     
[build]   Abandoned: 10 packages were abandoned.                               
[build]   Failed:    1 packages failed.                                        
[build] Runtime: 4.8 seconds total.

**Comment by immel-f** [comment]
The build seems to fail because of boost, which version of boost and which linux are you using?

**Comment by sheraz-rasib** [comment]
I am using Ubuntu 18.04 and I updated the latest boost version boost_1_82_0, but still getting same eroor?

**Comment by sheraz-rasib** [comment]
This issue is solved after restarting the system problem was boosted version. Thanks
