### ISSUE TITLE
Lanelet2_validation fail while catkin build

### ISSUE THREAD

**Issue by sheraz-rasib** [fzi-forschungszentrum-informatik/Lanelet2#315]
Errors     << lanelet2_validation:make /home/sheraz/catkin_ws/logs/lanelet2_validation/build.make.005.log                                                                                                  
/home/sheraz/catkin_ws/devel/.private/lanelet2_io/lib/liblanelet2_io.so: undefined reference to `boost::archive::detail::basic_oarchive::get_helper_collection()'
/home/sheraz/catkin_ws/devel/.private/lanelet2_io/lib/liblanelet2_io.so: undefined reference to `boost::archive::basic_binary_iarchive<boost::archive::binary_iarchive>::load_override(boost::archive::class_name_type&)'
/home/sheraz/catkin_ws/devel/.private/lanelet2_io/lib/liblanelet2_io.so: undefined reference to `boost::archive::archive_exception::archive_exception(boost::archive::archive_exception const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/sheraz/catkin_ws/devel/.private/lanelet2_validation/lib/lanelet2_validation/lanelet2_validate] Error 1
make[1]: *** [CMakeFiles/lanelet2_validation-lanelet2_validate-exec.dir/all] Error 2
make: *** [all] Error 2
cd /home/sheraz/catkin_ws/build/lanelet2_validation; catkin build --get-env lanelet2_validation | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...........................................................................................................................................................................................................
Failed     << lanelet2_validation:make              [ Exited with code 2 ]                                                                                                                                 
Failed    <<< lanelet2_validation                   [ 0.2 seconds ]                                                                                                                                        
Abandoned <<< lanelet2                              [ Unrelated job failed ]                                                                                                                               
___________________________________________________________________________________________________________________________________________________________________________________________________________
Errors     << lanelet2_examples:make /home/sheraz/catkin_ws/logs/lanelet2_examples/build.make.003.log                                                                                                      
/home/sheraz/catkin_ws/devel/.private/lanelet2_io/lib/liblanelet2_io.so: undefined reference to `boost::archive::detail::basic_oarchive::get_helper_collection()'
/home/sheraz/catkin_ws/devel/.private/lanelet2_io/lib/liblanelet2_io.so: undefined reference to `boost::archive::basic_binary_iarchive<boost::archive::binary_iarchive>::load_override(boost::archive::class_name_type&)'
/home/sheraz/catkin_ws/devel/.private/lanelet2_io/lib/liblanelet2_io.so: undefined reference to `boost::archive::archive_exception::archive_exception(boost::archive::archive_exception const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/sheraz/catkin_ws/devel/.private/lanelet2_examples/lib/lanelet2_examples/04_reading_and_writing] Error 1
make[1]: *** [CMakeFiles/lanelet2_examples-04_reading_and_writing-exec.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/sheraz/catkin_ws/devel/.private/lanelet2_io/lib/liblanelet2_io.so: undefined reference to `boost::archive::detail::basic_oarchive::get_helper_collection()'
/home/sheraz/catkin_ws/devel/.private/lanelet2_io/lib/liblanelet2_io.so: undefined reference to `boost::archive::basic_binary_iarchive<boost::archive::binary_iarchive>::load_override(boost::archive::class_name_type&)'
/home/sheraz/catkin_ws/devel/.private/lanelet2_io/lib/liblanelet2_io.so: undefined reference to `boost::archive::archive_exception::archive_exception(boost::archive::archive_exception const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/sheraz/catkin_ws/devel/.private/lanelet2_examples/lib/lanelet2_examples/06_routing] Error 1
make[1]: *** [CMakeFiles/lanelet2_examples-06_routing-exec.dir/all] Error 2
/home/sheraz/catkin_ws/devel/.private/lanelet2_io/lib/liblanelet2_io.so: undefined reference to `boost::archive::detail::basic_oarchive::get_helper_collection()'
/home/sheraz/catkin_ws/devel/.private/lanelet2_io/lib/liblanelet2_io.so: undefined reference to `boost::archive::basic_binary_iarchive<boost::archive::binary_iarchive>::load_override(boost::archive::class_name_type&)'
/home/sheraz/catkin_ws/devel/.private/lanelet2_io/lib/liblanelet2_io.so: undefined reference to `boost::archive::archive_exception::archive_exception(boost::archive::archive_exception const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/sheraz/catkin_ws/devel/.private/lanelet2_examples/lib/lanelet2_examples/07_matching] Error 1
make[1]: *** [CMakeFiles/lanelet2_examples-07_matching-exec.dir/all] Error 2
make: *** [all] Error 2
cd /home/sheraz/catkin_ws/build/lanelet2_examples; catkin build --get-env lanelet2_examples | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...........................................................................................................................................................................................................
Failed     << lanelet2_examples:make                [ Exited with code 2 ]                                                                                                                                 
Failed    <<< lanelet2_examples                     [ 0.3 seconds ]                                                                                                                                        
[build] Summary: 8 of 11 packages succeeded.                                                                                                                                                               
[build]   Ignored:   None.                                                                                                                                                                                 
[build]   Warnings:  None.                                                                                                                                                                                 
[build]   Abandoned: 1 packages were abandoned.                                                                                                                                                            
[build]   Failed:    2 packages failed.                                                                                                                                                                    
[build] Runtime: 1.0 seconds total.

**Comment by poggenhans** [comment]
Is this still an issue? Looks like your boost installation is missing a few required shared libraries (in particular `libboost-serialization.so`).
