### ISSUE TITLE
Remove dependency of mrt_cmake_modules

### ISSUE THREAD

**Issue by felixf4xu** [fzi-forschungszentrum-informatik/Lanelet2#319]
There are several issues of using [mrt_cmake_modules](https://github.com/KIT-MRT/mrt_cmake_modules):

1. it's very slow, because it includes lots of unnecessary/unused packages
2. it seems that it still use catkin
3. its `mrt_add_library` does not support STATIC library
4. ...

I can list more issues, big ones, small ones, but generally I think `ament_cmake` or plain `cmake` should be good enough, there is no need to introduce new dependencies.

**Comment by immel-f** [comment]
You can build Lanelet2 in conan without mrt_cmake_modules or catkin, instructions for that can be found in the [Readme](https://github.com/fzi-forschungszentrum-informatik/Lanelet2#readme). We also provide a docker image and pip installation. 

If you want to contribute an alternative build tooling working with e.g. ament, that would also be welcome!

**Comment by felixf4xu** [comment]
thanks for the update.

I read more on the source code and find that `ament_cmake` is mentioned in some change logs.

I will try will that and come back later.

**Comment by elkuno213** [comment]
I have completed a repository for the [plain-CMake Lanelet2 project](https://github.com/elkuno213/lanelet2-plain-cmake), which removes all dependencies on ROS and mrt_cmake_modules. You may refer to it for more details.
