### ISSUE TITLE
route.getLaneletMap() - object has no attribute

### ISSUE THREAD

**Issue by supertravio** [fzi-forschungszentrum-informatik/Lanelet2#32]
Hi,

We're following the examples here - https://github.com/fzi-forschungszentrum-informatik/Lanelet2/tree/master/lanelet2_routing - trying to get routing working in python but the `route.getLaneletMap()` line is throwing the following error: 

```
AttributeError: 'Route' object has no attribute 'getLaneletMap'
```

We tried checking what other properties are available and there is a `laneletMap` property but calling this returns the following:

```
TypeError: No to_python (by-value) converter found for C++ type: std::shared_ptr<lanelet::LaneletMap const>
```

Any suggestions?

Thanks,
trav.

**Comment by supertravio** [comment]
Looks like we didn't actually need laneletMap. We're up and running with

```
shortestPath = route.shortestPath()
```

**Comment by poggenhans** [comment]
But that was a valid issue. I updated the README and fixed the python binding for `laneletMap`. Thanks!

**Comment by autonomobil** [comment]
I have the same issue, what could be problem?
