### ISSUE TITLE
lanelet2_io [ Exited with code 2 ] 

### ISSUE THREAD

**Issue by JinXJinLeX** [fzi-forschungszentrum-informatik/Lanelet2#322]
![2023-10-24 12-53-31 的屏幕截图](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/assets/42336677/71449aa2-257b-49de-a15d-a31efc88ecc0)

**Comment by immel-f** [comment]
Sorry for the late reply, could you provide more information about your setup (which Ubuntu version are you using, what version are your installed libraries...). Lanelet2 is also available as a package for ROS and pip, so depending on your system you do not need to build it from source.

**Comment by JinXJinLeX** [comment]
Thank you for your reply! My Ubuntu version is 18.04, melodic, I installed Autoware.AI before, and I find that Lanelet2 already in my workspace as a package, shows "ros-melodic-lanelet2 已经是最新版 (1.0.1-1bionic.20201017.041713)。"
