### ISSUE TITLE
Broken Links within Mkdocs Documentation

### ISSUE THREAD

**Issue by DavUhll** [fzi-forschungszentrum-informatik/Lanelet2#330]
In the current state of the ``MkDocs`` documentation, numerous links are broken due to the targeting of ``README.md`` files that are copied before creating the documentation. E. g. click on  [Edit on GitHub](https://fzi-forschungszentrum-informatik.github.io/Lanelet2/lanelet2_core/).
This issue is raised to initiate a discussion on aligning the documentation for better coherence and usability.

The primary objective of this discussion is to explore strategies and potential solutions to streamline the Mkdocs documentation and its folder structure, ensuring that links are functional and direct users to the intended resources effectively.

Let's collaborate to enhance the usability and accessibility of the documentation.

Please feel free to provide your thoughts and suggestions in the comments below.

**Comment by m-naumann** [comment]
Is there a way with reasonable effort to modify links in this stage?

https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/4789fde6c3bafcd5a8d721d11c5d92870ca59a22/.github/workflows/cd.yaml#L141-L142
