### ISSUE TITLE
Route search by specifying impassable lanes

### ISSUE THREAD

**Issue by kosuke55** [fzi-forschungszentrum-informatik/Lanelet2#334]
Thank you for your great library. We have always been very helped in the development of [autoware](https://github.com/autowarefoundation/autoware.universe).

We are working on route generation when there are blocked lanes.
https://github.com/orgs/autowarefoundation/discussions/3599 
![image](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/assets/39142679/90c9c746-645e-4121-b64a-e1e49ed4450b)

```
routing_graph_ptr_->getRoute(start_lanelet, goal_lanelet, 0)
```
will find the shortest route from start_lanelet to goal_lanelet.

```
routing_graph_ptr_->getRouteVia(start_lanelet, via_lanelet, goal_lanelet, 0);
```
to find the shortest route from start_lanelet to goal_lanelet while passing through via_lanelet.

On the contrary, is it possible to designate lanes that cannot be passed through?
Or do you have any good ideas for implementation?

**Comment by kosuke55** [comment]
cc @ahmeddesokyebrahim
I asked about https://github.com/autowarefoundation/autoware.universe/pull/4524#discussion_r1485481008 here

**Comment by immel-f** [comment]
Specifying a lanelet as impassable for the routing graph is not explicitly supported to my knowledge, so I don't think there exists a nice way to do it. The routing costs are also calculated only once on construction of the graph, so even if you would implement a custom RoutingCost the graph would have to be rebuilt every time for dynamically impassable lanes.
