### ISSUE TITLE
Lanelet2 3D Viz

### ISSUE THREAD

**Issue by rreddy78** [fzi-forschungszentrum-informatik/Lanelet2#336]
Hello developers,

My question is not directly related to Lanelet2 library, but to its visualization. I am currently using JOSM which seems to be a pretty standard tool its visualization. But currently I need to visualize the map in 3D mainly to do a simple validation of the  orientation of the landmarks with respect to lanes. 

Is there any standard tool or method by which I can do this ? I am currently trying autoware map visualization (https://autowarefoundation.github.io/autoware-documentation/main/design/autoware-interfaces/components/map/) , but it does not seem to have it built in

Would be good to have a visualizer similar to what is available for OpenDrive (https://odrviewer.io/)

Thanks

**Comment by maxime-clem** [comment]
You can try the Vector Map Builder (https://tools.tier4.jp/vector_map_builder_ll2/). It allows visualizing and editing a lanelet map in 3D.

**Comment by poggenhans** [comment]
I also know of an `rviz` plugin: https://github.com/coincar-sim/lanelet_rviz_plugin_ros

**Comment by rreddy78** [comment]
Both seem to work good, though limited in the size of the lanelet2 files that can be loaded. Should be able to workaround that a bit ... Thanks!
