### ISSUE TITLE
Output of findWithin2d gives incomprehensible outputs when used on pointLayer of a known map

### ISSUE THREAD

**Issue by stevenbrills** [fzi-forschungszentrum-informatik/Lanelet2#337]
I'm trying to get the points of a lanelet2 map that are within a certain region. I've used multiple approaches to represent the 2D region including BoundingBox2d, Polygon, and Area. When using the findwithin2d function, I'm not able to get any points that I know are within the specified 2D region. None of the points have any elevation so they're all on the same plane. I tried making the bounding region very large ~100000 meters a side and I got a single point. I then made a custom bounding box defined just around that single point with sides of about 2 meters around. With this new bounding box centered about that point, I still get no results.

Does anyone have an idea of what might be going wrong here? I did remember reading that the PrimitiveLayer's search method is implemented as a namesake for the point layer. Does this mean the findwithin2d function is not expected to work with the points layer?

Thank you

Edit:
I'm using the lanelet2 packages that came with the ros2 galactic version. 

Here is a reference mini map that I'm using.
[test.zip](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/files/14952219/test.zip)

The search code line is:

`lanelet::geometry::findWithin2d(ll2_map_ptr_->pointLayer, lanelet::BoundingBox2d(lanelet::BasicPoint2d(-100,-100), lanelet::BasicPoint2d(100, 100)), 0.0);`

**Comment by immel-f** [comment]
Where is your projection origin when you load the map? I checked the map file, it contains lat/lon coordinates for the points and "local_x" / "local_y". When you load a map, the local coordinates are calculated based on the lat/lon coordinates and the origin however. You can print a point in the point layer to check. When I use findWithin2d with a bounding box that contains the coordinates of a point as printed above, the function behaves as expected.

**Comment by stevenbrills** [comment]
Okay, I was using it in the context of Autoware with the MGRS projection option. I may have overlooked the fact that the local_x and local_y tags are unique to Autoware and they override the projected lat/long values even if the MGRS projection option was specified. Thank you for bringing that to my attention. I guess I should then use the parser they provided so that the values get overwritten.
