### ISSUE TITLE
Automatically add role left and right to lanelet

### ISSUE THREAD

**Issue by Blitzur** [fzi-forschungszentrum-informatik/Lanelet2#338]
in the lanelet2_maps/josm/laneletpresets.xml there is the city road.
I mainly use this A LOT.
Every time you have to type at least L or R for left or right.
Is it possible, to change something in the laneletpresets.xml that it will automatically give the first way right and the second one left (or the other way around). This would speed up the workflow of creating maps by hand A LOT.
Thank you :)

**Comment by immel-f** [comment]
The laneletpresets.xml is related to JOSM, I don't know if there exists a way to do this there. I would be curious if you find a way to do it though :smile:
