### ISSUE TITLE
ShortestPath Function including lanechange doesn't work

### ISSUE THREAD

**Issue by eonsoo1** [fzi-forschungszentrum-informatik/Lanelet2#339]
Hello Everyone!

I have a question about shortestpath function.

I have a carla Town map osm file. So I apply shortestpath function to this map.
but you know? It's only applied to the connected lanelet. I mean, it doesn't work from lanelet1 to lanelet2.
I tried changing middle Line's attribute between them. but shortestpath still doesn't work,,,

Why doesn't the shortest path function from lanelet 1 to lanelet 2 apply when the subtype of the middle lane between the two lanes is dashed and the type is Line_thin? I understand that this function also applies to lane changes. Please Help me,,,,,

**Comment by poggenhans** [comment]
Hi @eonsoo1, without code example it is hard to give you an answer. If both lanelets are aligned (i.e. point in the same direction), drivable and there is a dashed line separating them, lanelet2 should find a path.
