### ISSUE TITLE
Representing lanes in construction zones

### ISSUE THREAD

**Issue by pranavashok** [fzi-forschungszentrum-informatik/Lanelet2#345]
Are there any guidelines on representing temporary lanes in construction zones in Lanelet2?

In Germany, for example, lanes that are shifted due to construction are defined by the typical yellow markings. In most cases, the underlying white markings would still be visible. Semantically, the lanes defined by the white markings are no longer drivable while traffic is forced to travel on the lanes defined by the yellow markings. What is the recommended way to represent this in Lanelet2? Open to hearing your opinions :-)

**Comment by immel-f** [comment]
There is no recommended way as of yet to do this, Lanelet2 in general has no proper support for different sets of lanelets or routes in the same map for the same vehicle type. You could theoretically add the construction lanelets to the map and make the original lanelets not drivable. AFAIK they should not appear in the routing graph then. This is probably quite error prone though. 

Usually we would just create a second map only with the construction state in it in these cases.
