### ISSUE TITLE
Unable to fetch python_dev_config dependency from bincrafters

### ISSUE THREAD

**Issue by kopp** [fzi-forschungszentrum-informatik/Lanelet2#361]
The build error in e.g. https://github.com/fzi-forschungszentrum-informatik/Lanelet2/actions/runs/10959285012/job/30432971204 seems to indicate, that we cannot get the python_dev_config dependency from the configured remote https://bincrafters.jfrog.io/artifactory/api/conan/public-conan (see .github/conan_dockerfile/Dockerfile):

```
#14 1.182 ERROR: Failed requirement 'python_dev_config/0.6@bincrafters/stable' from 'lanelet2/1.2.1@lanelet2/stable'
#14 1.182 ERROR: <!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="/favicon.ico"><title>JFrog Landing</title><link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800&display=swap" rel="stylesheet"><script>VERSION = "2024.2.251";
#14 1.182       API_PROXY_URL = "https://landing-api.jfrog.com/api/v1/";
#14 1.182       API_PROXY_URL_V2 = "https://landing-api.jfrog.com/api/v2/";
```

Visiting the page https://bincrafters.jfrog.io/artifactory/api/conan/public-conan brings me to a page that says

> Time flies when you’re having fun.
> Your 14-day trial may be over, but you have options!
> Need help choosing the right subscription or additional time on your trial? Just let us know and a DevOps expert will reach out to assist you.

**Comment by immel-f** [comment]
Thanks for digging up that error! After some further digging, it seems that the project that remote belonged to is down for good: [https://github.com/bincrafters/community/issues/1456](https://github.com/bincrafters/community/issues/1456) 

From the logs, it looks like conancenter does not have python_dev_config available, so we will need a bit of time to look into how to replace the discontinued bincrafters project. 

I am not too familiar with conan however, @poggenhans do you have an idea on how to proceed here?

**Comment by kopp** [comment]
I'm trying to 'just include' the code of the `python_dev_config` conan package in the lanelet codebase, and build it before building the `lanelet2` package, see [my branch](https://github.com/kopp/Lanelet2/tree/feature/include-copy-of-python_dev_config).

**Comment by kopp** [comment]
I seem to make some progress there.  Unfortunately it seems like I get test errors on `noetic`, but have no clue what's going on there, see [this run](https://github.com/kopp/Lanelet2/actions/runs/11223391821). On 'galactic' and 'humble' the tests pass and it also seems like the python packages are built.
