### ISSUE TITLE
How to include lanelet2 as a lib into a regular cmake C++ project?

### ISSUE THREAD

**Issue by chenran-li** [fzi-forschungszentrum-informatik/Lanelet2#39]
I have simulator which is a regular C++ project just using CmakeLists. Now, I want to use the lanelet2 as the map to locate the vehicle and plan the Vehicle's motion. when I try to include the lanelet2, since I didn't find any .a files and it is a big project, I didn't really get how to include it. It seems too complicated if I just copy all the codes in src and put  it in my project and write the CmakeList to include each files.

**Comment by poggenhans** [comment]
> It seems too complicated if I just copy all the codes in src and put it in my project and write the CmakeList to include each files.

No need for that. You can use projects created with catkin just like any other cmake project. You simply use `find_project` with that project and this will set `<project>_INCLUDE_DIRS`, `<project>_LIBRARIES` and `<project>_LIBRARY_DIRS>`. 

To make this work, cmake needs to know where to search for your package. You can do this either with `source /path/to/workspace/devel/setup.bash` which will setup `CMAKE_PREFIX_PATH` correctly or by setting `CMAKE_PREFIX_PATH` manually or by installing the workspace to your system (e.g. to /usr/local).

A sample `CMakeLists.txt` using *lanelet2_core* could look like this:
```cmake
cmake_minimum_required(VERSION 3.0)
project(foo)

find_package(lanelet2_core REQUIRED)
add_executable(foo_exe foo.cpp)
target_include_directories(foo_exe PUBLIC ${lanelet2_core_INCLUDE_DIRS})
target_link_libraries(foo_exe ${lanelet2_core_LIBRARIES})
```

**Comment by kuzen** [comment]
> > It seems too complicated if I just copy all the codes in src and put it in my project and write the CmakeList to include each files.
> 
> No need for that. You can use projects created with catkin just like any other cmake project. You simply use `find_project` with that project and this will set `<project>_INCLUDE_DIRS`, `<project>_LIBRARIES` and `<project>_LIBRARY_DIRS>`.
> 
> To make this work, cmake needs to know where to search for your package. You can do this either with `source /path/to/workspace/devel/setup.bash` which will setup `CMAKE_PREFIX_PATH` correctly or by setting `CMAKE_PREFIX_PATH` manually or by installing the workspace to your system (e.g. to /usr/local).
> 
> A sample `CMakeLists.txt` using _lanelet2_core_ could look like this:
> 
> ```cmake
> cmake_minimum_required(VERSION 3.0)
> project(foo)
> 
> find_package(lanelet2_core REQUIRED)
> add_executable(foo_exe foo.cpp)
> target_include_directories(foo_exe PUBLIC ${lanelet2_core_INCLUDE_DIRS})
> target_link_libraries(foo_exe ${lanelet2_core_LIBRARIES})
> ```

Hi. It doesn't work in my ubuntu 18 (mrt-cmake-module 1.03 + lanelet2 1.1.1). `lanelet2_core_INCLUDE_DIRS`

**Comment by poggenhans** [comment]
In the meantime, `mrt_cmake_modules` has switched to a target based approach, which is now the best practice for cmake.

The targets exported by `lanelet2_core` (and similarly for the other packages) will be set in `lanelet2_core_LIBRARIES` and `lanelet2_core_INCLUDE_DIRS` is no longer needed or used. A usage example would now look like below. It is just the same as above, but the `target_include_directories` directive is no longer necessary:

```cmake
cmake_minimum_required(VERSION 3.5)
project(foo)

find_package(lanelet2_core REQUIRED)
add_executable(foo_exe foo.cpp)
target_link_libraries(foo_exe PUBLIC ${lanelet2_core_LIBRARIES})
```

**Comment by elkuno213** [comment]
I have completed a repository for the [plain-cmake Lanelet2 project](https://github.com/elkuno213/lanelet2-plain-cmake), which removes all dependencies on ROS and mrt_cmake_modules. You may refer to it for more details.
