### ISSUE TITLE
Issues in catkin build 

### ISSUE THREAD

**Issue by qlyzhang** [fzi-forschungszentrum-informatik/Lanelet2#4]
When I do "catkin build", I encountered some issues.

`Workspace configuration appears valid.

NOTE: Forcing CMake to run for each package.
--------------------------------------------------------------------------------
[build] Found '11' packages in 0.0 seconds.                                    
[build] Updating package table.                                                
Starting  >>> catkin_tools_prebuild                                            
Finished  <<< catkin_tools_prebuild                 [ 3.7 seconds ]            
Starting  >>> mrt_cmake_modules                                                
Finished  <<< mrt_cmake_modules                     [ 2.9 seconds ]            
Starting  >>> lanelet2_core                                                    
Finished  <<< lanelet2_core                         [ 51.7 seconds ]           
Starting  >>> lanelet2_io                                                      
Starting  >>> lanelet2_maps                                                    
Starting  >>> lanelet2_traffic_rules                                           
Finished  <<< lanelet2_maps                         [ 3.2 seconds ]            
Finished  <<< lanelet2_traffic_rules                [ 19.8 seconds ]           
Starting  >>> lanelet2_routing                                                 
Finished  <<< lanelet2_io                           [ 38.8 seconds ]           
Starting  >>> lanelet2_projection                                              
Finished  <<< lanelet2_projection                   [ 9.8 seconds ]            
Finished  <<< lanelet2_routing                      [ 44.3 seconds ]           
Starting  >>> lanelet2_python                                                  
Starting  >>> lanelet2_validation                                              
Finished  <<< lanelet2_validation                   [ 32.9 seconds ]           
Finished  <<< lanelet2_python                       [ 1 minute and 8.3 seconds ]
Starting  >>> lanelet2_examples                                                
_______________________________________________________________________________
Warnings   << lanelet2_examples:make /home/neilzhang/Desktop/Research2/catkin_ws/logs/lanelet2_examples/build.make.000.log
CMakeFiles/lanelet2_examples-04_reading_and_writing-exec.dir/src/04_reading_and_writing/main.cpp.o:main.cpp:function part1LoadingAndWriting(): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
cd /home/neilzhang/Desktop/Research2/catkin_ws/build/lanelet2_examples; catkin build --get-env lanelet2_examples | catkin env -si  /usr/bin/make --jobserver-fds=3,4 -j; cd -
...............................................................................
Finished  <<< lanelet2_examples                     [ 25.9 seconds ]           
[build] Summary: All 11 packages succeeded!                                    
[build]   Ignored:   1 packages were skipped or are blacklisted.               
[build]   Warnings:  1 packages succeeded with warnings.                       
[build]   Abandoned: None.                                                     
[build]   Failed:    None.                                                     
[build] Runtime: 3 minutes and 37.8 seconds total.                             
[build] Note: Workspace packages have changed, please re-source setup files to use them.
Exception ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/home/neilzhang/.local/lib/python3.5/site-packages/trollius/base_events.py", line 395, in __del__
  File "/home/neilzhang/.local/lib/python3.5/site-packages/trollius/unix_events.py", line 65, in close
  File "/home/neilzhang/.local/lib/python3.5/site-packages/trollius/unix_events.py", line 166, in remove_signal_handler
  File "/usr/lib/python3.5/signal.py", line 47, in signal
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object`

I don't know how to fix this. I also have no idea which package failed in my installation. Could you please help me?

**Comment by poggenhans** [comment]
Are you referring to the crash in the last few lines or is this related to #5?

For the crash: The issue seems to that the package trollius of your local python installation interferes with catkin. Since this is python3.5, while catkin usually uses python2.7, I would recommend you to start there.

However lanelet2 is not related to the crash, so I will close this issue.

**Comment by qlyzhang** [comment]
Thank you very much!
