### ISSUE TITLE
lanelet centerline() return error?

### ISSUE THREAD

**Issue by liuyf5231** [fzi-forschungszentrum-informatik/Lanelet2#41]
1.use  tutorial.py,  i generate a map which contains a lanelet
2. read map from 1, use lanelet.centerline(),I think the output may be error

```
  LaneletMapPtr map = load(testMapPath, projection::UtmProjector(Origin({34.49233,109.04286})));
  ConstLanelet lanelet = map->laneletLayer.get(1000);
  std::cout<<lanelet.centerline();
```
the result is 
[id: 0 point ids: 0, 0, 0, 0, 0], something is error?

**Comment by m-naumann** [comment]
That just means that the linestring and the computed points do not have an ID (because they were computed after loading the map and are "not part of the map", so they won't be stored and cannot be accessed via `map->pointLayer.get(id)`).

Just look at the points and their coordinates.

**Comment by liuyf5231** [comment]
> That just means that the linestring and the computed points do not have an ID (because they were computed after loading the map and are "not part of the map", so they won't be stored and cannot be accessed via `map->pointLayer.get(id)`).
> 
> Just look at the points and their coordinates.

thanks!

**Comment by HadiElnemr** [comment]
I am facing the same issue with a map. I tried map.pointLayer.get(id) and it returns the point on the map and all points have an id on the map. When I try to get lanelet.centerline, it returns the 0 ids ConstLineString3d. What is wrong or how can I solve this please?

`map = lanelet2.io.load(osm_file_path, lanelet2.projection.CpmProjector(lanelet2.io.Origin(0,0))
lanelets = get_lanelets(map) 
print(lanelets[20])   # output:   [id: 1175, left id: 1019, right id: 1018]
lane_center = lanelet[20].centerline
print(lane_center)
# output:   [id: 0 point ids: 0, 0, 0, 0, 0]
`
