### ISSUE TITLE
can i use gpx to generate lanelets?

### ISSUE THREAD

**Issue by liuyf5231** [fzi-forschungszentrum-informatik/Lanelet2#42]
My idea is :
1.   I got 2 gpx file(eg. left.gpx and right.gpx ) , which include the left  linestring and right linestring
2.   import these 2 gpx file into josm, merge them, then convert to data layer
3.   construct lanelet by the data form step 2

it's ok?

**Comment by m-naumann** [comment]
Just give it a try
