### ISSUE TITLE
[Question] Traffic Sign Number

### ISSUE THREAD

**Issue by mitsudome-r** [fzi-forschungszentrum-informatik/Lanelet2#43]
About tagging the type for traffic signs, there is following description:
> The type is encoded as ISO 3166 region code + traffic sign number (e.g. de206 for a german stop sign)

I understand that `de` is ISO 3166 region code for Germany, but where did the traffic sign number come from? 
I saw that the numbers match with the image in lanelet2_maps/josm/style_images.zip, but are the numbers originally defined by Lanelet2 developers or are they based on some other reference?

**Comment by poggenhans** [comment]
They follow the German legislative (see the [German Wikipedia](https://de.wikipedia.org/wiki/Bildtafel_der_Verkehrszeichen_in_der_Bundesrepublik_Deutschland_seit_2017#Gefahrzeichen_nach_Anlage_1_(zu_%C2%A7_40_Absatz_6_und_7_StVO))).

**Comment by mitsudome-r** [comment]
I see.
Thank you!
