### ISSUE TITLE
Example of a Lanelet2 XML File 

### ISSUE THREAD

**Issue by mohannad19932** [fzi-forschungszentrum-informatik/Lanelet2#44]
Hello, 
I want to find an example of an XML File of a lanelet2 file .. where can I find it ?? 

Best Regards, 
Mohannad

**Comment by poggenhans** [comment]
In [lanelet2_maps](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/tree/master/lanelet2_maps/res)!!

**Comment by deepaktalwardt** [comment]
Hi Fabian,

Are there any other bigger Lanelet2 examples that are publicly available? I would like to try out features on a bigger map. Thanks.

**Comment by poggenhans** [comment]
You might consider looking into the [INTERACTION](https://interaction-dataset.com/) dataset. The maps are not very large, however. Apart from that, I am not aware of other maps that are available for free.
