### ISSUE TITLE
[Question] Map matching module

### ISSUE THREAD

**Issue by odel4y** [fzi-forschungszentrum-informatik/Lanelet2#45]
Hi!
In the original paper you mention a Lanelet2 "Matching" module. Looking at the code I could not find this module. Is it planned to release this module publicly?
Thanks!

**Comment by poggenhans** [comment]
Yes, we are currently working on the release. I hope we can ship it within the next 1-2 months.

**Comment by odel4y** [comment]
Thanks for the info! I am looking forward to it.

**Comment by m-naumann** [comment]
@odel4y you can find a preliminary version here: https://github.com/coincar-sim/lanelet2_matching
