### ISSUE TITLE
[Question] processMergingLanelets gives an assert

### ISSUE THREAD

**Issue by dymons** [fzi-forschungszentrum-informatik/Lanelet2#46]
Hi!
When searching for a route through the narrowing of the road from two-lane to single-lane, we have the following behavior. If the route is executed by one Lanelet, then the route will be successful, but when used on several Lanelet’s, a call is made to assert from the addPrevious functions.
https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/b802037f0703bc6035bfca6de174ba29b8fc9c35/lanelet2_routing/src/RouteBuilder.cpp#L570
I understand it, this is due to the fact that the source element RouteElement is already used in the route, and because we get this assert. Why could this happen? How can you solve this case at the stage of create cart if we need several Lanelet's or it solve software change?
One Lanelet (Good)
![good](https://user-images.githubusercontent.com/20445903/61806618-8764d280-ae27-11e9-8da6-9e3cd32a5a10.png)
 Several Lanelet’s(Bad)
![bad](https://user-images.githubusercontent.com/20445903/61806704-b67b4400-ae27-11e9-8e89-8696377c6cab.png)
Log Error
![log(1)](https://user-images.githubusercontent.com/20445903/61806739-c09d4280-ae27-11e9-8378-924fd3ec1d92.png)

**Comment by poggenhans** [comment]
Strange. The assert just ensures that the same edge isn't added twice to the routing graph. So something goes wrong here. Can you give me the part of the map where it fails?

**Comment by dymons** [comment]
Sure, I take of two version maps, bad and good version.
[map.zip](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/files/3431259/map.zip)

**Comment by poggenhans** [comment]
Sorry, I cannot trigger the assertion with your map. I ran the checker in lanelet2_validation on your bad.osm and it works fine (`./lanelet2_validate --lat 60 --lon 30 bad.osm`). The routing graph looks fine as well:
![image](https://user-images.githubusercontent.com/22795364/62379783-ea511a80-b547-11e9-90e0-102f773f09b3.png)

**Comment by dymons** [comment]
Yes, the graph is laid well. But when I try to find a route from lanelet 1123 to lanelet 1122 I get this assert.

```
fromlanelet = map.laneletLayer[1123]
toLanelet = map.laneletLayer[1122]
route = graph.getRoute(fromlanelet, toLanelet)
```

**Comment by dan-dan97** [comment]
I have the same problem. When I use getRoute between lanelets and there is any merging consisting of more then 2 following lanelets there are asserts in addPrevious and addFollowing. It seems that when the following or previous lanelet is going to be added this lanelet sometimes already exists.
So the function using addPrevious or addFollowing has to check if the added lanelet already exists. Or the other fix is to change "assert" to "if(...) return;" as I have done to solve the problem in the most simple way.

**Comment by poggenhans** [comment]
FYI, we that assert should be fixt in the current 0.9 release
