### ISSUE TITLE
How do I run the C++ examples after building inside docker?

### ISSUE THREAD

**Issue by deepaktalwardt** [fzi-forschungszentrum-informatik/Lanelet2#47]
I successfully built the docker image, started the container and tested that python is able to import lanelet2 correctly. However, how do I run the example C++ files provided? I'm specifically trying to run 06_routing example on the provided .osm example map. The repo does not list any steps to actually run the example. I would really appreciate the help. Thank you.

**Comment by poggenhans** [comment]
The steps for executing match the ones for executing ROS packages in general, so you can just refer to ROS or Catkin documentation. In short, you can just use `rosrun` to execute the examples when within the container: `rosrun lanelet2_examples 06_routing`. 

If you just want to run it together with the container, you would need the absolute path, though: `docker run --rm lanelet2 /home/developer/workspace/devel/lib/lanelet2_examples/06_routing`.
