### ISSUE TITLE
lanelet2 examples

### ISSUE THREAD

**Issue by BurkeyLai** [fzi-forschungszentrum-informatik/Lanelet2#48]
Hi, I successfully built the working space without docker but my local computer.
After I `source devel/setup.bash`, I try to execute the examples with `rosrun lanelet2_examples 01_dealing_with_lanelet_primitives` but nothing happen. No errors, no windows show up.
Is there anything I missed?

**Comment by poggenhans** [comment]
You didn't miss anything. It just means you successfully executed the example. It is not supposed to do or show anything. The interesting thing is the source code, not the output.

**Comment by autonomobil** [comment]
- [01 Dealing with lanelet primitives](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_examples/src/01_dealing_with_lanelet_primitives/main.cpp)

- [02 Regulatory elements](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_examples/src/02_regulatory_elements/main.cpp)

- [03 Lanelet map](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_examples/src/03_lanelet_map/main.cpp)

- [04 Reading and writing](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_examples/src/04_reading_and_writing/main.cpp)

- [05 Traffic rules](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_examples/src/05_traffic_rules/main.cpp)

- [06 Routing](
https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_examples/src/06_routing/main.cpp)
