### ISSUE TITLE
Issues with lanelet2_examples  

### ISSUE THREAD

**Issue by qlyzhang** [fzi-forschungszentrum-informatik/Lanelet2#5]
When I do catkin build, I got:

Workspace configuration appears valid.

NOTE: Forcing CMake to run for each package.
-------------------------------------------------------------------------------
[build] Found '11' packages in 0.0 seconds.                                    
[build] Updating package table.                                                
Starting  >>> catkin_tools_prebuild                                            
Finished  <<< catkin_tools_prebuild                 [ 1.9 seconds ]            
Starting  >>> mrt_cmake_modules                                                
Finished  <<< mrt_cmake_modules                     [ 2.5 seconds ]            
Starting  >>> lanelet2_core                                                    
Finished  <<< lanelet2_core                         [ 43.0 seconds ]           
Starting  >>> lanelet2_io                                                      
Starting  >>> lanelet2_maps                                                    
Starting  >>> lanelet2_traffic_rules                                           
Finished  <<< lanelet2_maps                         [ 3.2 seconds ]            
Finished  <<< lanelet2_traffic_rules                [ 20.3 seconds ]           
Starting  >>> lanelet2_routing                                                 
Finished  <<< lanelet2_io                           [ 42.1 seconds ]           
Starting  >>> lanelet2_projection                                              
Finished  <<< lanelet2_routing                      [ 40.5 seconds ]           
Finished  <<< lanelet2_projection                   [ 10.3 seconds ]           
Starting  >>> lanelet2_python                                                  
Starting  >>> lanelet2_validation                                              
Finished  <<< lanelet2_validation                   [ 32.4 seconds ]           
Finished  <<< lanelet2_python                       [ 1 minute and 9.4 seconds ]
Starting  >>> lanelet2_examples                                                
_______________________________________________________________________________
Warnings   << lanelet2_examples:make /home/neilzhang/Desktop/Research/catkin_ws/logs/lanelet2_examples/build.make.000.log
CMakeFiles/lanelet2_examples-04_reading_and_writing-exec.dir/src/04_reading_and_writing/main.cpp.o:main.cpp:function part1LoadingAndWriting(): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
cd /home/neilzhang/Desktop/Research/catkin_ws/build/lanelet2_examples; catkin build --get-env lanelet2_examples | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...............................................................................
Finished  <<< lanelet2_examples                     [ 26.5 seconds ]           
[build] Summary: All 11 packages succeeded!                                    
[build]   Ignored:   1 packages were skipped or are blacklisted.               
[build]   Warnings:  1 packages succeeded with warnings.                       
[build]   Abandoned: None.                                                     
[build]   Failed:    None.                                                     
[build] Runtime: 3 minutes and 26.9 seconds total.                             
[build] Note: Workspace packages have changed, please re-source setup files to use them.

Could you help me fix the warning "warning: the use of `tmpnam' is dangerous, better use `mkstemp' "?

**Comment by poggenhans** [comment]
Hi, this warning comes from one of our examples where we use a temporary file to write a map there.

The use of tmpnam is generally discouraged for security reasons, but here this is not an issue because I would not consider an example program a security vulnerability. I will look into silencing this warning, if I find the time.

**Comment by qlyzhang** [comment]
Thank you for your reply.
I tried to modify the code in /lanelet2_examples/src/04_reading_and_writing/main.cpp
I changed `std::string filename = tmpnam(nullptr);` to 
`std::string filename = "myfile" + std::to_string(rand());` in order to avoid error with "tmpnam"

Then I reinstall lanelet2 using your procedure, and I change the code like above before doing catkin build. Here is what I got:

[build] Found '11' packages in 0.0 seconds.                                    
[build] Updating package table.                                                
Starting  >>> catkin_tools_prebuild                                            
Finished  <<< catkin_tools_prebuild                 [ 1.8 seconds ]            
Starting  >>> mrt_cmake_modules                                                
Finished  <<< mrt_cmake_modules                     [ 2.3 seconds ]            
Starting  >>> lanelet2_core                                                    
Finished  <<< lanelet2_core                         [ 42.0 seconds ]           
Starting  >>> lanelet2_io                                                      
Starting  >>> lanelet2_maps                                                    
Starting  >>> lanelet2_traffic_rules                                           
Finished  <<< lanelet2_maps                         [ 3.2 seconds ]            
Finished  <<< lanelet2_traffic_rules                [ 19.7 seconds ]           
Starting  >>> lanelet2_routing                                                 
Finished  <<< lanelet2_io                           [ 41.0 seconds ]           
Starting  >>> lanelet2_projection                                              
Finished  <<< lanelet2_routing                      [ 40.7 seconds ]           
Finished  <<< lanelet2_projection                   [ 10.9 seconds ]           
Starting  >>> lanelet2_python                                                  
Starting  >>> lanelet2_validation                                              
Finished  <<< lanelet2_validation                   [ 40.7 seconds ]           
Finished  <<< lanelet2_python                       [ 1 minute and 9.2 seconds ]
Starting  >>> lanelet2_examples                                                
Finished  <<< lanelet2_examples                     [ 26.9 seconds ]           
[build] Summary: All 11 packages succeeded!                                    
[build]   Ignored:   1 packages were skipped or are blacklisted.               
[build]   Warnings:  None.                                                     
[build]   Abandoned: None.                                                     
[build]   Failed:    None.                                                     
[build] Runtime: 3 minutes and 24.6 seconds total.                             
[build] Note: Workspace packages have changed, please re-source setup files to use them.

The example package is ignored. Is it because I changed one line of code so that it is not consistent to CMakeList?

**Comment by poggenhans** [comment]
First off: This is just a warning that you are trying to fix, not an error. The build of the project was still sucessful.

Why do you say that the example package was ignored? In your logfie it says:

> Starting >>> lanelet2_examples
> Finished <<< lanelet2_examples [ 26.9 seconds ]

That means that the package build was sucessful.

**Comment by qlyzhang** [comment]
Sorry, my bad. By 'Ignored' I mean it said:
> [build] Ignored: 1 packages were skipped or are blacklisted.

And when I test 'import' to each package, it told me:
No module named 'lanelet2_examples'
So this package build was not successful. 
I guess the reason is I changed one line of your code from 
```c++
std::string filename = tmpnam(nullptr);
```
to
```c++
std::string filename = "myfile" + std::to_string(rand());
```
Maybe this change made the package incompatible. 
Could you help me fix this? I really appreciate your help. 
Thank you.

**Comment by poggenhans** [comment]
There is a simple explanation for this: There is no module named lanelet2_examples. The only python modules that lanelet2 offers are: core, io, projection, routing and traffic_rules. Your change did not break anything because there is nothing to break.

The example package only contains a python script to show you how to work with lanelet2 in python. But no modules.
