### ISSUE TITLE
[Error] Line types dashed_solid and solid_dashed are swapped

### ISSUE THREAD

**Issue by dan-dan97** [fzi-forschungszentrum-informatik/Lanelet2#50]
I've recognized that there is an error that dashed_solid and solid_dashed are swapped. For example lanelets that are separated with solid_dashed line have left relation AdjacentLeft and right relation Right.

**Comment by poggenhans** [comment]
Did you check the orientation of the linestring? The attribute is relative to the orientation of the linestring. If your lanelet looks like below, lanelet2 inverts the effect of the `solid_dashed`, meaning it is possible to do a lane change *into* the lanelet, but not out of it via its left bound.

```
<<<<<<<<<<<<< left: solid_dashed <<<<<<<<<<<

                  some lanelet

>>>>>>>>>>>>>>>>> right >>>>>>>>>>>>>>>>>>>>
```
