### ISSUE TITLE
[Question] How not to add previous lanelet's when forming a Route?

### ISSUE THREAD

**Issue by dymons** [fzi-forschungszentrum-informatik/Lanelet2#55]
When I try to find a route through several goals, use the function getRouteVia, it turns out that a path shorter than shortestPath appears in the route.
Because of this, we are not moving on shortestPath, and cut it. I suppose in the process of forming a Route, not only neighboring lanelet's are added, but also the previous ones.

For example:
I'm trying to drive start - > goal 1 - > goal 2 -> ... - >finish. At the time of loading the route getRouteVia(start, {goal 1}, goal 2), the next Route is obtained.
![FirstChange](https://user-images.githubusercontent.com/20445903/67273132-88f57380-f4c6-11e9-9a57-65faf257489b.png)
As a result, we are looking for the shortest path of movement, and we are not moving in the way that was supposed.
![SecondChange](https://user-images.githubusercontent.com/20445903/67273153-927edb80-f4c6-11e9-906f-1ddbd3e701f1.png)
Is there a way not to add previous lanelet's, so that the Route was formed only on the path shortestPath?

**Comment by poggenhans** [comment]
Thanks for reporting this. It seems you found a bug in how we assemble the route. Can you confirm that this problem goes away when you split the lanelet that crosses the intersection from top to right in two?

The reason that we process previous lanelets is that we want to find lanelets that diverge and then merge back into the original route. But these lanelets should always be adjacent to the shortest path. In your case that is clearly not the case.

**Comment by dymons** [comment]
Yes, it helped. Divided lanelet into two parts, and the route is built as expected. Thanks a lot!
Found the final route using the function getRouteVia(start, {goal 1}, goal 2)
![Change2](https://user-images.githubusercontent.com/20445903/67283113-bb5d9b80-f4db-11e9-832e-5d606631d0c0.png)
Find final path
![resultCgange](https://user-images.githubusercontent.com/20445903/67283309-1c856f00-f4dc-11e9-8680-a96f229d9bad.png)

**Comment by dymons** [comment]
Do you need this map for debugging? If Yes, you can give me your mail, I'll send it to you there.
