### ISSUE TITLE
Question: How to get a const view of the whole map

### ISSUE THREAD

**Issue by msmcconnell** [fzi-forschungszentrum-informatik/Lanelet2#60]
I would like to have one object that owns my LaneletMap object. However, other objects may need to use information from the map to make decisions. Is there a way I can return a const view of the underlying map such that the user objects cannot call any of the non-const functions?

So far the main option I see is 
```
lanelet::LaneletMap my_map; // Defined elsewhere 

LaneletMapConstUPtr getConstMap() {
  lanelet::ConstLanelets lanelets(my_map.laneletLayer.begin(), my_map.laneletLayer.end());
  lanelet::ConstAreas areas(my_map.areaLayer.begin(), my_map.areaLayer.end());
  return lanelet::utils::createConstMap(lanelets, areas);
}
```

Is this a reasonable approach or is there a better way to provide access to the map? 
Will this provide access to all the layers of the original map?
I believe this call would duplicate the contents of map, due to the std::vector constructor call, which seems very costly.

**Comment by m-naumann** [comment]
Hey @msmcconnell 

Is there a problem with the constness of the whole map? 

Otherwize, you could simply 
* pass a [const shared pointer](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/862e5aab5b80050a0355e5bcb2b886820ce7fc6e/lanelet2_core/include/lanelet2_core/Forward.h#L168)
* or load the map again as const map, for example using [lanelet2_interface_ros](https://github.com/coincar-sim/lanelet2_interface_ros) to ensure you load the same map everywhere

**Comment by msmcconnell** [comment]
@m-naumann Thanks for the response. For some reason I was not seeing that there was a forward for 
LaneletMapConstPtr, since I did see the shared pointer forward for the primitives, I was concerned that the LaneletMap did not have the same const correctness guarantees. The shared pointer meets my use case. I'll close this issue.
