### ISSUE TITLE
[Question] How to get all connected lanelets

### ISSUE THREAD

**Issue by msmcconnell** [fzi-forschungszentrum-informatik/Lanelet2#61]
How do I get the set of lanelets which a specific lanelet has direct connections to. For example, if I had a lanelet at a exit ramp, how do I get the lanelet the proceeds along the road as well as the lanelet which diverges onto the ramp? I can't seem to fine an example of querying "connects to" information in the repo, but maybe I am looking in the wrong places.

**Comment by msmcconnell** [comment]
It seems there are some methods provided by the RoutingGraph that achieve my goal such as
```
  LaneletPaths possiblePaths(const ConstLanelet& startPoint, uint32_t minLanelets, bool allowLaneChanges = false) const;
```
Is the only way to achieve this through the routing graph? How long do routing graphs take to build?

**Comment by poggenhans** [comment]
> How long do routing graphs take to build?

Why don't you try it out 😉?

You might want to have a look into our [example code](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_examples/src/06_routing/main.cpp) concerning `RoutingGraph`s. They are *the* object dedicated for querying neighbourhood information about lanelets.

**Comment by msmcconnell** [comment]
@poggenhans Thanks for confirming, I was under the impression the routing module was just for planning not for generalized connection information. I will dig into that some more now that the use case is clearer.
