### ISSUE TITLE
toArcCoordinates is ambiguous for points before the linestring 

### ISSUE THREAD

**Issue by msmcconnell** [fzi-forschungszentrum-informatik/Lanelet2#62]
In lanelet2 an ArcCoordinate is defined as such
```
struct ArcCoordinates {
  double length{0.};    //!< length along linestring
  double distance{0.};  //!< signed distance to linestring (left=positive)
};
```
The ArcCoordinate of a point relative to a linestring can be computed using the following function. 
```
/**
 *
 * @brief Transform a point to the coordinates of the linestring
 *
 * This computes the Distance along the LineString and distance to the
 * LineString for the point on the LineString that is closest to the input
 * point.
 */
template <typename LineString2dT>
ArcCoordinates toArcCoordinates(const LineString2dT& lineString, const BasicPoint2d& point);
```
Under normal circumstances this means a point lying between the two endpoints of the linestring will have its position reported as though it were referencing a Frenet frame located at the start point of the linestring. An example of this is shown by the green dot below.  
![image](https://user-images.githubusercontent.com/10292079/69971245-9a7e6200-14ed-11ea-9c16-aaf146e49bf8.png)
However, as shown by the red/orange dots this description is invalid for points lying inline with the end points or before or after the linestring. In this event the length is always set to 0 and the distance becomes the straight line distance from the point to the nearest endpoint. 

This in itself isn't a problem. The issue is that the difference between the red and orange point cannot be determined. So for every point which exists beyond the bounds of the linestring there is actually a second point with the same coordinates. I think a method for determining if the point is inline with the endpoint or beyond the ends of the linestring is needed.

**Comment by poggenhans** [comment]
Your observation is correct. Fresnet frames are not unique. Actually there are ambiguities at every point of the linestring.

You could find these cases by testing whether `interpolatedPointAtDistance` is `boost::equals` with `nearestPointAtDistance`.

**Comment by msmcconnell** [comment]
Thanks for identifying a work around. That seems like a very costly way of checking for the ambiguities. But a more general solution is not coming to my mind at the moment so, I have decided to implement specific logic with some location constraints for this as my use case allows that.
