### ISSUE TITLE
[Question] How to Handle Ambiguous Direction of Lanelet

### ISSUE THREAD

**Issue by findaheng** [fzi-forschungszentrum-informatik/Lanelet2#63]
In the "Lanelet2 Primitives" documentation (pictured below), it states that the library will handle the alignment of linestrings to ensure that lanelets are defined by a left and a right linestring that point in the same direction. 

<img width="881" alt="Screen Shot 2019-12-11 at 10 20 30 PM" src="https://user-images.githubusercontent.com/20452859/70687626-9a583200-1c64-11ea-9ac1-7f53e8289455.png">

How does this handle lanelets in which it is ambiguous exactly which of its linestring bounds are inverted, such as the second lanelet below, where the orange arrows represent the sequential ordering of the linestring's points:

<img width="307" alt="Screen Shot 2019-12-11 at 10 50 12 PM" src="https://user-images.githubusercontent.com/20452859/70689349-e5744400-1c68-11ea-9e5b-9f18225262a5.png">

Is there a convention to avoid this kind of ambiguity, i.e. an additional linestring must be defined, rather than "reusing" the same linestring for both the left and right bounds of two opposing lanelets?

**Comment by m-naumann** [comment]
The linestrings themselves are not inverted in the meaning of the order of points is not actually changed, but the lanelet that needs the inverted linestring points to a (new/additional) linestring with additional information `inverted_=true` in case this is necessary. The underlying points, however, are the same, so if you change them in the inverted version, you also change the uninverted version. See also https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/c42f7ac9716f539c7c0761fa64e0005d1923820b/lanelet2_core/include/lanelet2_core/primitives/LineString.h#L188

In your example, enumerating the linestrings from 1 (left) to 5 (right), 
* if 2 is left and 3 is right for the "?" lanelet, then the left bound is actually the inverted linestring 2 and 
* in case 2 is right and 3 is left then again the left bound is inverted linestring 3
