### ISSUE TITLE
[Question]  Shortest Path Problem on a large map

### ISSUE THREAD

**Issue by dymons** [fzi-forschungszentrum-informatik/Lanelet2#69]
The question is how to work with large map sizes. JOSM starts not to cope with large volumes of the map, there are lags and friezes. There was an idea to use a primitive like [tile](https://wiki.openstreetmap.org/wiki/Tiles) to divide the map into smaller parts.
But there is a problem with finding a route on the tiles.
The simplest idea that comes to mind is to use classical algorithms to find the A* or Dijkstra route on tiles. But the following questions arise:
- How to create the tiles?
- How to match tiles with each other?
- How to form (connect) the final map from the resulting set of tiles?
- How to search for a route in a reasonable time (if there is a large graph)?

I have managed to find the following possible approaches to solving the problem of finding a route between tiles:
[Customizable Route Planning in Road Networks.](https://www.microsoft.com/en-us/research/wp-content/uploads/2013/01/crp_web_130724.pdf)
[An Efficient Path Computation Model for Hierarchically Structured Topographical Road Maps.](https://www.cse.msu.edu/~pramanik/research/papers/papers/tkde2002.pdf)

What do you think about this task and do you have any ideas for solving it?

**Comment by poggenhans** [comment]
We haven't really considered handling maps with sizes where tiling becomes necessary yet. Our concept was that handling large maps is a problem that can mostly be done outside the core library of lanelet2. What you would basically do is:
1. Bin the primitives within the map into tiles and save these tiles.
2. For each entrance into a tile compute the routing costs to the exit of the tile. That basically gives you a subsampled version of the "global" routing graph.

When you want to compute a route, you would:
1. load this subsampled graph, 
2. compute the route and load all tiles that where used. 
3. Then you only have to assemble the map form the loaded tiles
4. and replace parts with the same ID that were loaded from multiple tiles
5. pass the result to lanelet2_routing and compute your route as you normally would.

This procedure requires few to no changes to lanelet2 itself. We might think about making the route search faster (currently we use Dijkstra, A* would be smarter for large maps) and adding helpers for combining maps with overlap loaded from several files.

**Comment by dymons** [comment]
@poggenhans, thank you for the proposed algorithm. I have a few questions:
- How will you combine several files into one map?
- What should the maps have in common to combine them?

Oh, yeah, that would be awesome.
> We might think about making the route search faster (currently we use Dijkstra, A* would be smarter for large maps) and adding helpers for combining maps with overlap loaded from several files.

**Comment by poggenhans** [comment]
> How will you combine several files into one map?

If the two maps A and B are disjoint, you could just add the primitives form the first to the second. If they are not, you would have to find the set of Ids which are present in both A and B (assuming Ids actually refer to a unique object across both files). And then in map B you find all usages of this Id (e.g. linestrings using this point) and replace the duplicate with the primitive from A. And then you add all things in B except the duplicates to A.

**Comment by dymons** [comment]
@poggenhans, thank you for that clarification!
