### ISSUE TITLE
How to use Lanelet2 in python3?

### ISSUE THREAD

**Issue by Yuchen-Tao** [fzi-forschungszentrum-informatik/Lanelet2#75]
Hello,
Because I want to write a python3 node in ros, I want to know how can I use Lanelet2 in Python3. I am now following the python tutorial, when I run the code in a python3 virtual environment it fails:
`Traceback (most recent call last):
  File "./tutorial.py", line 2, in <module>
    import lanelet2
  File "/home/irtauto/autoenv_ws/devel/lib/python2.7/dist-packages/lanelet2/__init__.py", line 12, in <module>
    module = import_module(__name__ + "." + module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: dynamic module does not define module export function (PyInit_traffic_rules)
`
In python2 environment I don't get this error. 
Also, I followed the instruction to use catkin build for python3, and it built my python3 test node successfully. But when I try to run the node, I get the same error as above. Similarly, when I change the shebang  #! /usr/bin/env python3 to #! /usr/bin/env python2, the node runs successfully.
Do you have any suggestions on how to use Lanelet2 in python3 code? Or it is not supported yet?

**Comment by poggenhans** [comment]
Your error indicates the python bindings are still built with python2 enabled. From afar, it is hard to say what went wrong. You should have a look at the cmake output. If you see things like `Found PythonInterp: /usr/bin/python2 (found version "2.7.15")` in cmakes build output, you didn't configure catkin correctly to find the correct python version.

**Comment by Yuchen-Tao** [comment]
> Your error indicates the python bindings are still built with python2 enabled. From afar, it is hard to say what went wrong. You should have a look at the cmake output. If you see things like `Found PythonInterp: /usr/bin/python2 (found version "2.7.15")` in cmakes build output, you didn't configure catkin correctly to find the correct python version.

Thank you for the quick response! The reason is because that ros will automatically add '/opt/ros/kinetic/lib/python2.7/dist-packages' to the python path and it is in the first place. So I added `sys.path.remove('/opt/ros/melodic/lib/python2.7/dist-packages')` in the beginning of the code and the error disappeared.
