### ISSUE TITLE
catkin build failed: 8 packages were abandoned;1 packages failed.

### ISSUE THREAD

**Issue by noone3001** [fzi-forschungszentrum-informatik/Lanelet2#84]
Sorry to bother you. I catkin build the whole project step by step according to the build manual in README.md , but it will display this error:

CMake Error at /catkin_ws/src/mrt_cmake_modules/cmake/Modules/FindAutoDeps.cmake:74 (list):
list sub-command REMOVE_ITEM requires list to be present.
Call Stack (most recent call first):
/catkin_ws/src/mrt_cmake_modules/cmake/Modules/FindAutoDeps.cmake:176 (_cleanup_libraries)
/catkin_ws/src/mrt_cmake_modules/cmake/Modules/FindAutoDeps.cmake:211 (_find_dep)
CMakeLists.txt:19 (find_package)

Could you help me ? Looking forward to your reply.

**Comment by poggenhans** [comment]
Just update mrt_cmake_modules. We fixed that problem yesterday.

**Comment by noone3001** [comment]
Thank you for your reply.
