### ISSUE TITLE
[Question]  meaning of routingCostId

### ISSUE THREAD

**Issue by DarrenWong** [fzi-forschungszentrum-informatik/Lanelet2#85]
Dear FZI,

I am reading the example of lanelet2-routing in https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_examples/src/06_routing/main.cpp
and want to understand the meaning of routingCostId.
```
 Optional<routing::LaneletPath> shortestPath = routingGraph->shortestPath(lanelet, toLanelet, 0);
```
```
  /** @brief Retrieve a shortest path between 'start' and 'end'.
   *
   *  Will find a shortest path using Djikstra's shortest path algorithm and the routing cost calculated by the
   * routing cost module with the respective ID. Be aware that the shortest path may contain lane changes,
   * i.e. lanelets that are parallel and not only adjacent.
   *  @param from Start lanelet to find a shortest path
   *  @param to End lanelet to find a shortest path
   *  @param routingCostId ID of RoutingCost module to determine shortest path
   *  @param withLaneChanges if false, the shortest path will not contain lane changes */
  Optional<LaneletPath> shortestPath(const ConstLanelet& from, const ConstLanelet& to, RoutingCostId routingCostId = {},
                                     bool withLaneChanges = true) const;
```

Is that means routingcostid=0 conenct to the __Distance-based calculation__ in RoutingCost.h and 1 connect to the __Travel time-based calculation__?
```
 *  As of now, two modules are implemented which should satisfy basic needs:
 *    1. Distance-based calculation
 *    2. Travel time-based calculation
```

**Comment by poggenhans** [comment]
The routing cost ids correspond to the index within the `routingCosts` parameter that was passed to `RoutingGraph::build`. By default, these are the ones returned by  [defaultRoutingCosts()](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_routing/include/lanelet2_routing/RoutingCost.h#L122).

That means if you don't pass anything to `RoutingGraph::build`, the routing costs IDs will work as you guessed.

**Comment by DarrenWong** [comment]
Got it and thx. And I think the para in defaultRoutingCosts mostly related to the cost of a lane change in distance and timing~

```
inline RoutingCostPtrs defaultRoutingCosts() {
  return RoutingCostPtrs{std::make_shared<RoutingCostDistance>(10.), std::make_shared<RoutingCostTravelTime>(5.)};
}
```
