### ISSUE TITLE
Manual Installation: 0 of 11 packages succeeded.

### ISSUE THREAD

**Issue by arvindkyutech** [fzi-forschungszentrum-informatik/Lanelet2#92]
I am doing manual installation. On running catkin build command. It gives an error: 0 of 11 packages succeeded. I have already checked mrt_cmake_modules is latest one. I am using ubuntu 16.04 and i have installed ros-kinetic.

...........................................................................................................................................
Failed     << catkin_tools_prebuild:cmake           [ Exited with code 1 ]                                                                 
Failed    <<< catkin_tools_prebuild                 [ 0.0 seconds ]                                                                        
Abandoned <<< mrt_cmake_modules                     [ Unrelated job failed ]                                                               
Abandoned <<< lanelet2_core                         [ Unrelated job failed ]                                                               
Abandoned <<< lanelet2_io                           [ Unrelated job failed ]                                                               
Abandoned <<< lanelet2_maps                         [ Unrelated job failed ]                                                               
Abandoned <<< lanelet2_projection                   [ Unrelated job failed ]                                                               
Abandoned <<< lanelet2_traffic_rules                [ Unrelated job failed ]                                                               
Abandoned <<< lanelet2_routing                      [ Unrelated job failed ]                                                               
Abandoned <<< lanelet2_python                       [ Unrelated job failed ]                                                               
Abandoned <<< lanelet2_examples                     [ Unrelated job failed ]                                                               
Abandoned <<< lanelet2_validation                   [ Unrelated job failed ]                                                               
[build] Summary: 0 of 11 packages succeeded.                                                                                               
[build]   Ignored:   1 packages were skipped or are blacklisted.                                                                           
[build]   Warnings:  None.                                                                                                                 
[build]   Abandoned: 10 packages were abandoned.                                                                                           
[build]   Failed:    1 packages failed.                                                                                                    
[build] Runtime: 0.1 seconds total.

**Comment by poggenhans** [comment]
Your build output is lacking the actual error message a few lines above.

From what I can see, the build process didn't even start because something fundamental was missing. I suspect you forgot to `source /opt/ros/kinetic/setup.bash` before building.

**Comment by arvindkyutech** [comment]
Thank You for your quick reply. I have done **source /opt/ros/kinetic/setup.bash** , but it is not working. Complete error message is as follows:
/catkin_ws$ sudo catkin build
--------------------------------------------------------------
Profile:                     default
Extending:                   None
Workspace:                   /home/arvind
--------------------------------------------------------------
Build Space:        [exists] /home/arvind/build
Devel Space:        [exists] /home/arvind/devel
Install Space:      [unused] /home/arvind/install
Log Space:          [exists] /home/arvind/logs
Source Space:       [exists] /home/arvind/src
DESTDIR:            [unused] None
--------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
--------------------------------------------------------------
Additional CMake Args:       -DCMAKE_BUILD_TYPE=RelWithDebInfo
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
--------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
--------------------------------------------------------------


--------------------------------------------------------------
WARNING: Your workspace is not extending any other result
space, but it is set to use a `linked` devel space layout.
This requires the `catkin` CMake package in your source space
in order to be built.
--------------------------------------------------------------

[build] Found '11' packages in 0.0 seconds.                                                                                       
[build] Package table is up to date.                                                                                              
Warning: generated devel space setup files have been deleted.
Starting  >>> catkin_tools_prebuild                                                                                               
__________________________________________________________________________________________________________________________________
Errors     << catkin_tools_prebuild:cmake /home/arvind/logs/catkin_tools_prebuild/build.cmake.009.log                             
CMake Error at /home/arvind/build/catkin_tools_prebuild/CMakeLists.txt:12 (message):
  The catkin CMake module was not found, but it is required to build a linked
  workspace.  To resolve this, please do one of the following, and try
  building again.



   1. Source the setup.sh file from an existing catkin workspace:
      source SETUP_FILE



   2. Extend another catkin workspace's result (install or devel) space:
      catkin config --extend RESULT_SPACE



   3. Set `catkin_DIR` to the directory containing `catkin-config.cmake`:
      catkin config --cmake-args -Dcatkin_DIR=CATKIN_CMAKE_CONFIG_PATH



   4. Add the catkin source package to your workspace's source space:
      cd SOURCE_SPACE && git clone https://github.com/ros/catkin.git


cd /home/arvind/build/catkin_tools_prebuild; catkin build --get-env catkin_tools_prebuild | catkin env -si  /usr/bin/cmake /home/arvind/build/catkin_tools_prebuild --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/arvind/devel/.private/catkin_tools_prebuild -DCMAKE_INSTALL_PREFIX=/home/arvind/install -DCMAKE_BUILD_TYPE=RelWithDebInfo; cd -
..................................................................................................................................
Failed     << catkin_tools_prebuild:cmake           [ Exited with code 1 ]                                                        
Failed    <<< catkin_tools_prebuild                 [ 0.0 seconds ]                                                               
Abandoned <<< mrt_cmake_modules                     [ Unrelated job failed ]                                                      
Abandoned <<< lanelet2_core                         [ Unrelated job failed ]                                                      
Abandoned <<< lanelet2_io                           [ Unrelated job failed ]                                                      
Abandoned <<< lanelet2_maps                         [ Unrelated job failed ]                                                      
Abandoned <<< lanelet2_projection                   [ Unrelated job failed ]                                                      
Abandoned <<< lanelet2_traffic_rules                [ Unrelated job failed ]                                                      
Abandoned <<< lanelet2_routing                      [ Unrelated job failed ]                                                      
Abandoned <<< lanelet2_python                       [ Unrelated job failed ]                                                      
Abandoned <<< lanelet2_examples                     [ Unrelated job failed ]                                                      
Abandoned <<< lanelet2_validation                   [ Unrelated job failed ]                                                      
[build] Summary: 0 of 11 packages succeeded.                                                                                      
[build]   Ignored:   1 packages were skipped or are blacklisted.                                                                  
[build]   Warnings:  None.                                                                                                        
[build]   Abandoned: 10 packages were abandoned.                                                                                  
[build]   Failed:    1 packages failed.                                                                                           
[build] Runtime: 0.1 seconds total.

**Comment by arvindkyutech** [comment]
Thank You for your quick reply. I have done `source /opt/ros/kinetic/setup.bash` but error exists. 
Complete error message is as follows. (Again Thank you for your help)
/catkin_ws$ sudo catkin build
Profile:                     default
Extending:                   None
Workspace:                   /home/arvind

Build Space:        [exists] /home/arvind/build
Devel Space:        [exists] /home/arvind/devel
Install Space:      [unused] /home/arvind/install
Log Space:          [exists] /home/arvind/logs
Source Space:       [exists] /home/arvind/src
DESTDIR:            [unused] None

Devel Space Layout:          linked
Install Space Layout:        None

Additional CMake Args:       -DCMAKE_BUILD_TYPE=RelWithDebInfo
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False

Whitelisted Packages:        None
Blacklisted Packages:        None

WARNING: Your workspace is not extending any other result
space, but it is set to use a `linked` devel space layout.
This requires the `catkin` CMake package in your source space
in order to be built.


[build] Found '11' packages in 0.0 seconds.                                                                                       
[build] Package table is up to date.                                                                                              
Warning: generated devel space setup files have been deleted.
Starting  >>> catkin_tools_prebuild    


Errors     << catkin_tools_prebuild:cmake /home/arvind/logs/catkin_tools_prebuild/build.cmake.009.log                             
CMake Error at /home/arvind/build/catkin_tools_prebuild/CMakeLists.txt:12 (message):
  The catkin CMake module was not found, but it is required to build a linked
  workspace.  To resolve this, please do one of the following, and try
  building again.



   1. Source the setup.sh file from an existing catkin workspace:
      source SETUP_FILE



   2. Extend another catkin workspace's result (install or devel) space:
      catkin config --extend RESULT_SPACE



   3. Set `catkin_DIR` to the directory containing `catkin-config.cmake`:
      catkin config --cmake-args -Dcatkin_DIR=CATKIN_CMAKE_CONFIG_PATH



   4. Add the catkin source package to your workspace's source space:
      cd SOURCE_SPACE && git clone https://github.com/ros/catkin.git


cd /home/arvind/build/catkin_tools_prebuild; catkin build --get-env catkin_tools_prebuild | catkin env -si  /usr/bin/cmake /home/arvind/build/catkin_tools_prebuild --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/arvind/devel/.private/catkin_tools_prebuild -DCMAKE_INSTALL_PREFIX=/home/arvind/install -DCMAKE_BUILD_TYPE=RelWithDebInfo; cd -


Failed     << catkin_tools_prebuild:cmake           [ Exited with code 1 ]                                                        
Failed    <<< catkin_tools_prebuild                 [ 0.0 seconds ]                                                               
Abandoned <<< mrt_cmake_modules                     [ Unrelated job failed ]                                                      
Abandoned <<< lanelet2_core                         [ Unrelated job failed ]                                                      
Abandoned <<< lanelet2_io                           [ Unrelated job failed ]                                                      
Abandoned <<< lanelet2_maps                         [ Unrelated job failed ]                                                      
Abandoned <<< lanelet2_projection                   [ Unrelated job failed ]                                                      
Abandoned <<< lanelet2_traffic_rules                [ Unrelated job failed ]                                                      
Abandoned <<< lanelet2_routing                      [ Unrelated job failed ]                                                      
Abandoned <<< lanelet2_python                       [ Unrelated job failed ]                                                      
Abandoned <<< lanelet2_examples                     [ Unrelated job failed ]                                                      
Abandoned <<< lanelet2_validation                   [ Unrelated job failed ]                                                      
[build] Summary: 0 of 11 packages succeeded.                                                                                      
[build]   Ignored:   1 packages were skipped or are blacklisted.                                                                  
[build]   Warnings:  None.                                                                                                        
[build]   Abandoned: 10 packages were abandoned.                                                                                  
[build]   Failed:    1 packages failed.                                                                                           
[build] Runtime: 0.1 seconds total.

**Comment by poggenhans** [comment]
> Extending: None

This is your problem. You build the workspace without sourcing ros first (and btw you shouldn't use `sudo` to build your workspace). To fix that you have to clean the workspace, source again and then build again. The order in which you do that is important:
```
catkin clean -y
source /opt/ros/kinetic/setup.bash
catkin build
```

**Comment by arvindkyutech** [comment]
All works perfect. Thank You for your help.
