### ISSUE TITLE
How to reload cache after calculating centerline for lanelet in python?

### ISSUE THREAD

**Issue by arvindkyutech** [fzi-forschungszentrum-informatik/Lanelet2#95]
I have a lanelet named lanelet1. Initially, I calculate it's centerline using lanelet1.centerline. But, when I modify the points in lanelets. It's centerline doesn't get modified.

**Comment by poggenhans** [comment]
Seems like we forgot to register `Lanelet::resetCache` for python. We'll fix that..

**Comment by arvindkyutech** [comment]
Thank you for quick reply

**Comment by poggenhans** [comment]
Should be fixed with 94a9c00e7330c5638335cf65b9d35d6f77bd6b0a
