### ISSUE TITLE
SpeedLimit, RegulatoryElement,RegulatoryElementLayer class cannot be instantiated from python?

### ISSUE THREAD

**Issue by arvindkyutech** [fzi-forschungszentrum-informatik/Lanelet2#98]
When I instantiate SpeedLimit, RegulatoryElement, RegulatoryElementLayer class it shows following error that it can instantiate it from Python. Is it mandatory to use C++ to use this classes.

Traceback (most recent call last):
  File "LaneletExample.py", line 447, in <module>
    Examples()
  File "LaneletExample.py", line 22, in Examples
    RegulatoryElem()
  File "LaneletExample.py", line 426, in RegulatoryElem
    sl =lanelet2.core.SpeedLimit() #This class cannot be instantiated using python   
RuntimeError: This class cannot be instantiated from Python

Traceback (most recent call last):
  File "LaneletExample.py", line 447, in <module>
    Examples()
  File "LaneletExample.py", line 22, in Examples
    RegulatoryElem()
  File "LaneletExample.py", line 429, in RegulatoryElem
    re = lanelet2.core.RegulatoryElement()
RuntimeError: This class cannot be instantiated from Python

Traceback (most recent call last):
  File "LaneletExample.py", line 447, in <module>
    Examples()
  File "LaneletExample.py", line 22, in Examples
    RegulatoryElem()
  File "LaneletExample.py", line 430, in RegulatoryElem
    re1 = lanelet2.core.RegulatoryElementLayer()
RuntimeError: This class cannot be instantiated from Python

**Comment by poggenhans** [comment]
RegulatoryElement and RegulatoryElementLayer cannot be instanciated in C++ too. RegulatoryElement is an abstract base class that can only be instanciated via its children. And a RegulatoryElementLayer exists only in context of a map:
```python
llmap = lanelet2.core.laneletMap()
reLayer = llmap.regulatoryElementLayer
```

SpeedLimit should be instanciable. It seems its constructor was not inherited from TrafficSign as intended. Well fix that.

**Comment by arvindkyutech** [comment]
Can you share class diagram for the classes. It becomes difficult to know which method is abstract in base class. Also **inspect.isabstract(lanelet2.core.RegulatoryElement)** returns **False** as output. Can you please help in, How to  create new RegulatoryElement in python?

**Comment by poggenhans** [comment]
Because the classes in python are exported from C++, the type information in Python may be misleading. If you want to know the inheritance as python sees it, you might have a look at the [python bindings source code](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_python/python_api/core.cpp#L783).

For the "real" inheritance diagram, the [doxygen doc](http://docs.ros.org/api/lanelet2_core/html/doxygen/classlanelet_1_1RegulatoryElement.html) could be helpful.

**Comment by poggenhans** [comment]
This issue has been inactive for a while. I'm assuming the original problem has been resolved.
