### ISSUE TITLE
Handle merging and forking lanes in a highway

### ISSUE THREAD

**Issue by corot** [fzi-forschungszentrum-informatik/Lanelet2#99]
How to identify when a highway narrows from 3 to 2 lanes, like here?
![image](https://user-images.githubusercontent.com/322610/77284450-0ccfb800-6d12-11ea-8929-71b7706bbb08.png)
(the road goes from right to left)

If I call fullLane or remainingLane on a Route comprising the yellow dots, I get a continuous lane containing lanelets 74492, 74542 and 74495, so I have no way to identify that the lane is actually disappearing. This is important because it implies a lane change. I would expect to get instead only 74492 and 74542. Sure, lane index will decrease from 2 to 1, but if the same happen in the left lane, lane index will remain 0. I could also identify that 74495 has two preceding lanelets, but which one is the external (disappearing) one? (in anyway this looks too cumbersome)

How do you usually handle these canses? Am I missing something? Or should the map be different, without lanelet 74542?

Thanks a lot

**Comment by m-naumann** [comment]
Hi, lanelet 74542 should only be the part that becomes smaller and ends, so the actual "final part of the third lane". The red linestring in the middle of 74493 does not exist; instead, lane changes are possible anywhere along the boarder, as long as the marking is dashed and not solid. See for example lanelet E in Fig. 2 in [the publication](https://www.mrt.kit.edu/z/publ/download/2018/Poggenhans2018Lanelet2.pdf). Then `remainingLane` will end in 74542 in your case.

**Comment by corot** [comment]
Thanks for the fast answer. So the typical maps you use don't contain the merging lanelet? E.g., OSM highways are as in your paper?
Actually,,, where can I find example maps?

**Comment by m-naumann** [comment]
In lanelet2, there are no lanelets that "force" a lanechange at a particular position. Lane changes between lanes are possible wherever the traffic rules allow.

The mapping example is here: https://github.com/fzi-forschungszentrum-informatik/Lanelet2/tree/master/lanelet2_maps/res

The highway part looks like this (josm screenshot): 
![image](https://user-images.githubusercontent.com/22504347/77311787-113fa500-6d01-11ea-8363-517f8e5bf4e9.png)

**Comment by poggenhans** [comment]
Did I understand correctly that only 74492, 74542 and 74495 are part of the route? Then it is obvious that the lane does not end at lanelet 74542, because from the perspective of the route, no merging is happening, since lanelet 74493 is not part of the route.

**Comment by corot** [comment]
> Did I understand correctly that only 74492, 74542 and 74495 are part of the route? Then it is obvious that the lane does not end at lanelet 74542, because from the perspective of the route, no merging is happening, since lanelet 74493 is not part of the route.

right

**Comment by corot** [comment]
So the right map for the above situation would be something like:
![image](https://user-images.githubusercontent.com/322610/77604987-201f9500-6f57-11ea-8a89-d05fd643543e.png)
right?

**Comment by m-naumann** [comment]
yes

**Comment by corot** [comment]
thanks!
